<?xml version="1.0" encoding="UTF-8"?>
<testsuite tests="360" skipped="0" errors="316" failures="0" id="0" name="Raptoreum_Test_Suite" time="1.41566">
<testcase assertions="1060" classname="arith_uint256_tests" name="basics" time="0.045808">
</testcase>
<testcase assertions="3328" classname="arith_uint256_tests" name="shifts" time="0.009621">
</testcase>
<testcase assertions="520" classname="arith_uint256_tests" name="unaryOperators" time="0.002689">
</testcase>
<testcase assertions="34" classname="arith_uint256_tests" name="bitwiseOperators" time="0.001332">
</testcase>
<testcase assertions="2560" classname="arith_uint256_tests" name="comparison" time="0.006324">
</testcase>
<testcase assertions="2818" classname="arith_uint256_tests" name="plusMinus" time="0.006333">
</testcase>
<testcase assertions="15" classname="arith_uint256_tests" name="multiply" time="0.000846">
</testcase>
<testcase assertions="12" classname="arith_uint256_tests" name="divide" time="0.002431">
</testcase>
<testcase assertions="527" classname="arith_uint256_tests" name="methods" time="0.001857">
</testcase>
<testcase assertions="79" classname="arith_uint256_tests" name="bignum_SetCompact" time="0.000965">
</testcase>
<testcase assertions="20" classname="arith_uint256_tests" name="getmaxcoverage" time="0.000854">
</testcase>
<testcase assertions="19" classname="addrman_tests" name="addrman_simple" time="0.001426">
</testcase>
<testcase assertions="9" classname="addrman_tests" name="addrman_ports" time="0.001304">
</testcase>
<testcase assertions="22" classname="addrman_tests" name="addrman_select" time="0.010091">
</testcase>
<testcase assertions="40" classname="addrman_tests" name="addrman_new_collisions" time="0.001019">
</testcase>
<testcase assertions="164" classname="addrman_tests" name="addrman_tried_collisions" time="0.033519">
</testcase>
<testcase assertions="12" classname="addrman_tests" name="addrman_find" time="0.000889">
</testcase>
<testcase assertions="5" classname="addrman_tests" name="addrman_create" time="0.000862">
</testcase>
<testcase assertions="6" classname="addrman_tests" name="addrman_delete" time="0.000872">
</testcase>
<testcase assertions="4108" classname="addrman_tests" name="addrman_getaddr" time="0.130276">
</testcase>
<testcase assertions="1029" classname="addrman_tests" name="caddrinfo_get_tried_bucket_legacy" time="0.005046">
</testcase>
<testcase assertions="3071" classname="addrman_tests" name="caddrinfo_get_new_bucket_legacy" time="0.013169">
</testcase>
<testcase assertions="1029" classname="addrman_tests" name="caddrinfo_get_tried_bucket" time="0.03176">
</testcase>
<testcase assertions="3582" classname="addrman_tests" name="caddrinfo_get_new_bucket" time="0.163748">
</testcase>
<testcase assertions="18" classname="addrman_tests" name="addrman_serialization" time="0.002562">
</testcase>
<testcase assertions="135" classname="addrman_tests" name="addrman_selecttriedcollision" time="0.011931">
</testcase>
<testcase assertions="104" classname="addrman_tests" name="addrman_noevict" time="0.015238">
</testcase>
<testcase assertions="77" classname="addrman_tests" name="addrman_evictionworks" time="0.01191">
</testcase>
<testcase assertions="3" classname="amount_tests" name="MoneyRangeTest" time="0.00091">
</testcase>
<testcase assertions="34" classname="amount_tests" name="GetFeeTest" time="0.001909">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""
- file: amount_tests.cpp
- line: 79
]]></error><system-err><![CDATA[Failures detected in:
- test case: amount_tests/GetFeeTest
- file: amount_tests.cpp
- line: 20
]]></system-err>
</testcase>
<testcase assertions="1" classname="amount_tests" name="BinaryOperatorTest" time="0.000102">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""BinaryOperatorTest" fixture ctor"
- file: amount_tests.cpp
- line: 84
]]></error><system-err><![CDATA[Failures detected in:
- test case: amount_tests/BinaryOperatorTest
- file: amount_tests.cpp
- line: 84
]]></system-err>
</testcase>
<testcase assertions="1" classname="amount_tests" name="ToStringTest" time="9.1e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""ToStringTest" fixture ctor"
- file: amount_tests.cpp
- line: 101
]]></error><system-err><![CDATA[Failures detected in:
- test case: amount_tests/ToStringTest
- file: amount_tests.cpp
- line: 101
]]></system-err>
</testcase>
<testcase assertions="1" classname="allocator_tests" name="arena_tests" time="8.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""arena_tests" fixture ctor"
- file: allocator_tests.cpp
- line: 16
]]></error><system-err><![CDATA[Failures detected in:
- test case: allocator_tests/arena_tests
- file: allocator_tests.cpp
- line: 16
]]></system-err>
</testcase>
<testcase assertions="1" classname="allocator_tests" name="lockedpool_tests_mock" time="6.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""lockedpool_tests_mock" fixture ctor"
- file: allocator_tests.cpp
- line: 163
]]></error><system-err><![CDATA[Failures detected in:
- test case: allocator_tests/lockedpool_tests_mock
- file: allocator_tests.cpp
- line: 163
]]></system-err>
</testcase>
<testcase assertions="1" classname="allocator_tests" name="lockedpool_tests_live" time="6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""lockedpool_tests_live" fixture ctor"
- file: allocator_tests.cpp
- line: 212
]]></error><system-err><![CDATA[Failures detected in:
- test case: allocator_tests/lockedpool_tests_live
- file: allocator_tests.cpp
- line: 212
]]></system-err>
</testcase>
<testcase assertions="1" classname="base32_tests" name="base32_testvectors" time="6.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""base32_testvectors" fixture ctor"
- file: base32_tests.cpp
- line: 12
]]></error><system-err><![CDATA[Failures detected in:
- test case: base32_tests/base32_testvectors
- file: base32_tests.cpp
- line: 12
]]></system-err>
</testcase>
<testcase assertions="1" classname="base58_tests" name="base58_EncodeBase58" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""base58_EncodeBase58" fixture ctor"
- file: base58_tests.cpp
- line: 21
]]></error><system-err><![CDATA[Failures detected in:
- test case: base58_tests/base58_EncodeBase58
- file: base58_tests.cpp
- line: 21
]]></system-err>
</testcase>
<testcase assertions="1" classname="base58_tests" name="base58_DecodeBase58" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""base58_DecodeBase58" fixture ctor"
- file: base58_tests.cpp
- line: 41
]]></error><system-err><![CDATA[Failures detected in:
- test case: base58_tests/base58_DecodeBase58
- file: base58_tests.cpp
- line: 41
]]></system-err>
</testcase>
<testcase assertions="1" classname="base64_tests" name="base64_testvectors" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""base64_testvectors" fixture ctor"
- file: base64_tests.cpp
- line: 12
]]></error><system-err><![CDATA[Failures detected in:
- test case: base64_tests/base64_testvectors
- file: base64_tests.cpp
- line: 12
]]></system-err>
</testcase>
<testcase assertions="1" classname="bech32_tests" name="bip173_testvectors_valid" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""bip173_testvectors_valid" fixture ctor"
- file: bech32_tests.cpp
- line: 25
]]></error><system-err><![CDATA[Failures detected in:
- test case: bech32_tests/bip173_testvectors_valid
- file: bech32_tests.cpp
- line: 25
]]></system-err>
</testcase>
<testcase assertions="1" classname="bech32_tests" name="bip173_testvectors_invalid" time="6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""bip173_testvectors_invalid" fixture ctor"
- file: bech32_tests.cpp
- line: 45
]]></error><system-err><![CDATA[Failures detected in:
- test case: bech32_tests/bip173_testvectors_invalid
- file: bech32_tests.cpp
- line: 45
]]></system-err>
</testcase>
<testcase assertions="1" classname="bip32_tests" name="bip32_test1" time="6.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""bip32_test1" fixture ctor"
- file: bip32_tests.cpp
- line: 141
]]></error><system-err><![CDATA[Failures detected in:
- test case: bip32_tests/bip32_test1
- file: bip32_tests.cpp
- line: 141
]]></system-err>
</testcase>
<testcase assertions="1" classname="bip32_tests" name="bip32_test2" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""bip32_test2" fixture ctor"
- file: bip32_tests.cpp
- line: 145
]]></error><system-err><![CDATA[Failures detected in:
- test case: bip32_tests/bip32_test2
- file: bip32_tests.cpp
- line: 145
]]></system-err>
</testcase>
<testcase assertions="1" classname="bip32_tests" name="bip32_test3" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""bip32_test3" fixture ctor"
- file: bip32_tests.cpp
- line: 149
]]></error><system-err><![CDATA[Failures detected in:
- test case: bip32_tests/bip32_test3
- file: bip32_tests.cpp
- line: 149
]]></system-err>
</testcase>
<testcase assertions="1" classname="bip39_tests" name="bip39_vectors" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""bip39_vectors" fixture ctor"
- file: bip39_tests.cpp
- line: 25
]]></error><system-err><![CDATA[Failures detected in:
- test case: bip39_tests/bip39_vectors
- file: bip39_tests.cpp
- line: 25
]]></system-err>
</testcase>
<testcase assertions="1" classname="blockchain_tests" name="get_difficulty_for_very_low_target" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""get_difficulty_for_very_low_target" fixture ctor"
- file: blockchain_tests.cpp
- line: 46
]]></error><system-err><![CDATA[Failures detected in:
- test case: blockchain_tests/get_difficulty_for_very_low_target
- file: blockchain_tests.cpp
- line: 46
]]></system-err>
</testcase>
<testcase assertions="1" classname="blockchain_tests" name="get_difficulty_for_low_target" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""get_difficulty_for_low_target" fixture ctor"
- file: blockchain_tests.cpp
- line: 51
]]></error><system-err><![CDATA[Failures detected in:
- test case: blockchain_tests/get_difficulty_for_low_target
- file: blockchain_tests.cpp
- line: 51
]]></system-err>
</testcase>
<testcase assertions="1" classname="blockchain_tests" name="get_difficulty_for_mid_target" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""get_difficulty_for_mid_target" fixture ctor"
- file: blockchain_tests.cpp
- line: 56
]]></error><system-err><![CDATA[Failures detected in:
- test case: blockchain_tests/get_difficulty_for_mid_target
- file: blockchain_tests.cpp
- line: 56
]]></system-err>
</testcase>
<testcase assertions="1" classname="blockchain_tests" name="get_difficulty_for_high_target" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""get_difficulty_for_high_target" fixture ctor"
- file: blockchain_tests.cpp
- line: 61
]]></error><system-err><![CDATA[Failures detected in:
- test case: blockchain_tests/get_difficulty_for_high_target
- file: blockchain_tests.cpp
- line: 61
]]></system-err>
</testcase>
<testcase assertions="1" classname="blockchain_tests" name="get_difficulty_for_very_high_target" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""get_difficulty_for_very_high_target" fixture ctor"
- file: blockchain_tests.cpp
- line: 66
]]></error><system-err><![CDATA[Failures detected in:
- test case: blockchain_tests/get_difficulty_for_very_high_target
- file: blockchain_tests.cpp
- line: 66
]]></system-err>
</testcase>
<testcase assertions="1" classname="blockencodings_tests" name="SimpleRoundTripTest" time="8.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""SimpleRoundTripTest" fixture ctor"
- file: blockencodings_tests.cpp
- line: 55
]]></error><system-err><![CDATA[Failures detected in:
- test case: blockencodings_tests/SimpleRoundTripTest
- file: blockencodings_tests.cpp
- line: 55
]]></system-err>
</testcase>
<testcase assertions="1" classname="blockencodings_tests" name="NonCoinbasePreforwardRTTest" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""NonCoinbasePreforwardRTTest" fixture ctor"
- file: blockencodings_tests.cpp
- line: 138
]]></error><system-err><![CDATA[Failures detected in:
- test case: blockencodings_tests/NonCoinbasePreforwardRTTest
- file: blockencodings_tests.cpp
- line: 138
]]></system-err>
</testcase>
<testcase assertions="1" classname="blockencodings_tests" name="SufficientPreforwardRTTest" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""SufficientPreforwardRTTest" fixture ctor"
- file: blockencodings_tests.cpp
- line: 208
]]></error><system-err><![CDATA[Failures detected in:
- test case: blockencodings_tests/SufficientPreforwardRTTest
- file: blockencodings_tests.cpp
- line: 208
]]></system-err>
</testcase>
<testcase assertions="1" classname="blockencodings_tests" name="EmptyBlockRoundTripTest" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""EmptyBlockRoundTripTest" fixture ctor"
- file: blockencodings_tests.cpp
- line: 259
]]></error><system-err><![CDATA[Failures detected in:
- test case: blockencodings_tests/EmptyBlockRoundTripTest
- file: blockencodings_tests.cpp
- line: 259
]]></system-err>
</testcase>
<testcase assertions="1" classname="blockencodings_tests" name="TransactionsRequestSerializationTest" time="5.9e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""TransactionsRequestSerializationTest" fixture ctor"
- file: blockencodings_tests.cpp
- line: 303
]]></error><system-err><![CDATA[Failures detected in:
- test case: blockencodings_tests/TransactionsRequestSerializationTest
- file: blockencodings_tests.cpp
- line: 303
]]></system-err>
</testcase>
<testcase assertions="1" classname="blockencodings_tests" name="TransactionsRequestDeserializationMaxTest" time="6.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""TransactionsRequestDeserializationMaxTest" fixture ctor"
- file: blockencodings_tests.cpp
- line: 326
]]></error><system-err><![CDATA[Failures detected in:
- test case: blockencodings_tests/TransactionsRequestDeserializationMaxTest
- file: blockencodings_tests.cpp
- line: 326
]]></system-err>
</testcase>
<testcase assertions="1" classname="blockencodings_tests" name="TransactionsRequestDeserializationOverflowTest" time="6.2e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""TransactionsRequestDeserializationOverflowTest" fixture ctor"
- file: blockencodings_tests.cpp
- line: 341
]]></error><system-err><![CDATA[Failures detected in:
- test case: blockencodings_tests/TransactionsRequestDeserializationOverflowTest
- file: blockencodings_tests.cpp
- line: 341
]]></system-err>
</testcase>
<testcase assertions="200" classname="blockfilter_tests" name="gcsfilter_test" time="0.009153">
</testcase>
<testcase assertions="8" classname="blockfilter_tests" name="blockfilter_basic_test" time="9.5e-05">
</testcase>
<testcase assertions="42" classname="blockfilter_tests" name="blockfilters_json_test" time="0.000666">
</testcase>
<testcase assertions="1" classname="bloom_tests" name="bloom_create_insert_serialize" time="0.000113">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""bloom_create_insert_serialize" fixture ctor"
- file: bloom_tests.cpp
- line: 26
]]></error><system-err><![CDATA[Failures detected in:
- test case: bloom_tests/bloom_create_insert_serialize
- file: bloom_tests.cpp
- line: 26
]]></system-err>
</testcase>
<testcase assertions="1" classname="bloom_tests" name="bloom_create_insert_serialize_with_tweak" time="6.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""bloom_create_insert_serialize_with_tweak" fixture ctor"
- file: bloom_tests.cpp
- line: 57
]]></error><system-err><![CDATA[Failures detected in:
- test case: bloom_tests/bloom_create_insert_serialize_with_tweak
- file: bloom_tests.cpp
- line: 57
]]></system-err>
</testcase>
<testcase assertions="1" classname="bloom_tests" name="bloom_create_insert_key" time="6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""bloom_create_insert_key" fixture ctor"
- file: bloom_tests.cpp
- line: 85
]]></error><system-err><![CDATA[Failures detected in:
- test case: bloom_tests/bloom_create_insert_key
- file: bloom_tests.cpp
- line: 85
]]></system-err>
</testcase>
<testcase assertions="1" classname="bloom_tests" name="bloom_match" time="6.2e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""bloom_match" fixture ctor"
- file: bloom_tests.cpp
- line: 109
]]></error><system-err><![CDATA[Failures detected in:
- test case: bloom_tests/bloom_match
- file: bloom_tests.cpp
- line: 109
]]></system-err>
</testcase>
<testcase assertions="1" classname="bloom_tests" name="dip2_bloom_match" time="6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""dip2_bloom_match" fixture ctor"
- file: bloom_tests.cpp
- line: 178
]]></error><system-err><![CDATA[Failures detected in:
- test case: bloom_tests/dip2_bloom_match
- file: bloom_tests.cpp
- line: 178
]]></system-err>
</testcase>
<testcase assertions="1" classname="bloom_tests" name="dip2_bloom_update" time="5.9e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""dip2_bloom_update" fixture ctor"
- file: bloom_tests.cpp
- line: 248
]]></error><system-err><![CDATA[Failures detected in:
- test case: bloom_tests/dip2_bloom_update
- file: bloom_tests.cpp
- line: 248
]]></system-err>
</testcase>
<testcase assertions="1" classname="bloom_tests" name="merkle_block_1" time="7.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""merkle_block_1" fixture ctor"
- file: bloom_tests.cpp
- line: 278
]]></error><system-err><![CDATA[Failures detected in:
- test case: bloom_tests/merkle_block_1
- file: bloom_tests.cpp
- line: 278
]]></system-err>
</testcase>
<testcase assertions="1" classname="bloom_tests" name="merkle_block_2" time="6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""merkle_block_2" fixture ctor"
- file: bloom_tests.cpp
- line: 319
]]></error><system-err><![CDATA[Failures detected in:
- test case: bloom_tests/merkle_block_2
- file: bloom_tests.cpp
- line: 319
]]></system-err>
</testcase>
<testcase assertions="1" classname="bloom_tests" name="merkle_block_2_with_update_none" time="7.1e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""merkle_block_2_with_update_none" fixture ctor"
- file: bloom_tests.cpp
- line: 374
]]></error><system-err><![CDATA[Failures detected in:
- test case: bloom_tests/merkle_block_2_with_update_none
- file: bloom_tests.cpp
- line: 374
]]></system-err>
</testcase>
<testcase assertions="1" classname="bloom_tests" name="merkle_block_3_and_serialize" time="7.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""merkle_block_3_and_serialize" fixture ctor"
- file: bloom_tests.cpp
- line: 426
]]></error><system-err><![CDATA[Failures detected in:
- test case: bloom_tests/merkle_block_3_and_serialize
- file: bloom_tests.cpp
- line: 426
]]></system-err>
</testcase>
<testcase assertions="1" classname="bloom_tests" name="merkle_block_4" time="5.9e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""merkle_block_4" fixture ctor"
- file: bloom_tests.cpp
- line: 465
]]></error><system-err><![CDATA[Failures detected in:
- test case: bloom_tests/merkle_block_4
- file: bloom_tests.cpp
- line: 465
]]></system-err>
</testcase>
<testcase assertions="1" classname="bloom_tests" name="merkle_block_4_test_p2pubkey_only" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""merkle_block_4_test_p2pubkey_only" fixture ctor"
- file: bloom_tests.cpp
- line: 511
]]></error><system-err><![CDATA[Failures detected in:
- test case: bloom_tests/merkle_block_4_test_p2pubkey_only
- file: bloom_tests.cpp
- line: 511
]]></system-err>
</testcase>
<testcase assertions="1" classname="bloom_tests" name="merkle_block_4_test_update_none" time="5.9e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""merkle_block_4_test_update_none" fixture ctor"
- file: bloom_tests.cpp
- line: 534
]]></error><system-err><![CDATA[Failures detected in:
- test case: bloom_tests/merkle_block_4_test_update_none
- file: bloom_tests.cpp
- line: 534
]]></system-err>
</testcase>
<testcase assertions="1" classname="bloom_tests" name="rolling_bloom" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""rolling_bloom" fixture ctor"
- file: bloom_tests.cpp
- line: 562
]]></error><system-err><![CDATA[Failures detected in:
- test case: bloom_tests/rolling_bloom
- file: bloom_tests.cpp
- line: 562
]]></system-err>
</testcase>
<testcase assertions="1" classname="bls_tests" name="bls_sethexstr_tests" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""bls_sethexstr_tests" fixture ctor"
- file: bls_tests.cpp
- line: 14
]]></error><system-err><![CDATA[Failures detected in:
- test case: bls_tests/bls_sethexstr_tests
- file: bls_tests.cpp
- line: 14
]]></system-err>
</testcase>
<testcase assertions="1" classname="bls_tests" name="bls_sig_tests" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""bls_sig_tests" fixture ctor"
- file: bls_tests.cpp
- line: 32
]]></error><system-err><![CDATA[Failures detected in:
- test case: bls_tests/bls_sig_tests
- file: bls_tests.cpp
- line: 32
]]></system-err>
</testcase>
<testcase assertions="1" classname="bls_tests" name="batch_verifier_tests" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""batch_verifier_tests" fixture ctor"
- file: bls_tests.cpp
- line: 115
]]></error><system-err><![CDATA[Failures detected in:
- test case: bls_tests/batch_verifier_tests
- file: bls_tests.cpp
- line: 115
]]></system-err>
</testcase>
<testcase assertions="1" classname="bswap_tests" name="bswap_tests" time="6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""bswap_tests" fixture ctor"
- file: bswap_tests.cpp
- line: 12
]]></error><system-err><![CDATA[Failures detected in:
- test case: bswap_tests/bswap_tests
- file: bswap_tests.cpp
- line: 12
]]></system-err>
</testcase>
<testcase assertions="1" classname="checkdatasig_tests" name="checkdatasig_test" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""checkdatasig_test" fixture ctor"
- file: checkdatasig_tests.cpp
- line: 83
]]></error><system-err><![CDATA[Failures detected in:
- test case: checkdatasig_tests/checkdatasig_test
- file: checkdatasig_tests.cpp
- line: 83
]]></system-err>
</testcase>
<testcase assertions="1" classname="checkqueue_tests" name="test_CheckQueue_Correct_Zero" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_CheckQueue_Correct_Zero" fixture ctor"
- file: checkqueue_tests.cpp
- line: 177
]]></error><system-err><![CDATA[Failures detected in:
- test case: checkqueue_tests/test_CheckQueue_Correct_Zero
- file: checkqueue_tests.cpp
- line: 177
]]></system-err>
</testcase>
<testcase assertions="1" classname="checkqueue_tests" name="test_CheckQueue_Correct_One" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_CheckQueue_Correct_One" fixture ctor"
- file: checkqueue_tests.cpp
- line: 185
]]></error><system-err><![CDATA[Failures detected in:
- test case: checkqueue_tests/test_CheckQueue_Correct_One
- file: checkqueue_tests.cpp
- line: 185
]]></system-err>
</testcase>
<testcase assertions="1" classname="checkqueue_tests" name="test_CheckQueue_Correct_Max" time="7.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_CheckQueue_Correct_Max" fixture ctor"
- file: checkqueue_tests.cpp
- line: 193
]]></error><system-err><![CDATA[Failures detected in:
- test case: checkqueue_tests/test_CheckQueue_Correct_Max
- file: checkqueue_tests.cpp
- line: 193
]]></system-err>
</testcase>
<testcase assertions="1" classname="checkqueue_tests" name="test_CheckQueue_Correct_Random" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_CheckQueue_Correct_Random" fixture ctor"
- file: checkqueue_tests.cpp
- line: 201
]]></error><system-err><![CDATA[Failures detected in:
- test case: checkqueue_tests/test_CheckQueue_Correct_Random
- file: checkqueue_tests.cpp
- line: 201
]]></system-err>
</testcase>
<testcase assertions="1" classname="checkqueue_tests" name="test_CheckQueue_Catches_Failure" time="6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_CheckQueue_Catches_Failure" fixture ctor"
- file: checkqueue_tests.cpp
- line: 212
]]></error><system-err><![CDATA[Failures detected in:
- test case: checkqueue_tests/test_CheckQueue_Catches_Failure
- file: checkqueue_tests.cpp
- line: 212
]]></system-err>
</testcase>
<testcase assertions="1" classname="checkqueue_tests" name="test_CheckQueue_Recovers_From_Failure" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_CheckQueue_Recovers_From_Failure" fixture ctor"
- file: checkqueue_tests.cpp
- line: 240
]]></error><system-err><![CDATA[Failures detected in:
- test case: checkqueue_tests/test_CheckQueue_Recovers_From_Failure
- file: checkqueue_tests.cpp
- line: 240
]]></system-err>
</testcase>
<testcase assertions="1" classname="checkqueue_tests" name="test_CheckQueue_UniqueCheck" time="6.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_CheckQueue_UniqueCheck" fixture ctor"
- file: checkqueue_tests.cpp
- line: 264
]]></error><system-err><![CDATA[Failures detected in:
- test case: checkqueue_tests/test_CheckQueue_UniqueCheck
- file: checkqueue_tests.cpp
- line: 264
]]></system-err>
</testcase>
<testcase assertions="1" classname="checkqueue_tests" name="test_CheckQueue_Memory" time="6.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_CheckQueue_Memory" fixture ctor"
- file: checkqueue_tests.cpp
- line: 299
]]></error><system-err><![CDATA[Failures detected in:
- test case: checkqueue_tests/test_CheckQueue_Memory
- file: checkqueue_tests.cpp
- line: 299
]]></system-err>
</testcase>
<testcase assertions="1" classname="checkqueue_tests" name="test_CheckQueue_FrozenCleanup" time="6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_CheckQueue_FrozenCleanup" fixture ctor"
- file: checkqueue_tests.cpp
- line: 326
]]></error><system-err><![CDATA[Failures detected in:
- test case: checkqueue_tests/test_CheckQueue_FrozenCleanup
- file: checkqueue_tests.cpp
- line: 326
]]></system-err>
</testcase>
<testcase assertions="1" classname="checkqueue_tests" name="test_CheckQueueControl_Locks" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_CheckQueueControl_Locks" fixture ctor"
- file: checkqueue_tests.cpp
- line: 365
]]></error><system-err><![CDATA[Failures detected in:
- test case: checkqueue_tests/test_CheckQueueControl_Locks
- file: checkqueue_tests.cpp
- line: 365
]]></system-err>
</testcase>
<testcase assertions="1" classname="cachemap_tests" name="cachemap_test" time="6.1e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""cachemap_test" fixture ctor"
- file: cachemap_tests.cpp
- line: 53
]]></error><system-err><![CDATA[Failures detected in:
- test case: cachemap_tests/cachemap_test
- file: cachemap_tests.cpp
- line: 53
]]></system-err>
</testcase>
<testcase assertions="1" classname="cachemultimap_tests" name="cachemultimap_test" time="6.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""cachemultimap_test" fixture ctor"
- file: cachemultimap_tests.cpp
- line: 63
]]></error><system-err><![CDATA[Failures detected in:
- test case: cachemultimap_tests/cachemultimap_test
- file: cachemultimap_tests.cpp
- line: 63
]]></system-err>
</testcase>
<testcase assertions="1" classname="coins_tests" name="coins_cache_simulation_test" time="7.9e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""coins_cache_simulation_test" fixture ctor"
- file: coins_tests.cpp
- line: 111
]]></error><system-err><![CDATA[Failures detected in:
- test case: coins_tests/coins_cache_simulation_test
- file: coins_tests.cpp
- line: 111
]]></system-err>
</testcase>
<testcase assertions="1" classname="coins_tests" name="updatecoins_simulation_test" time="0.000102">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""updatecoins_simulation_test" fixture ctor"
- file: coins_tests.cpp
- line: 279
]]></error><system-err><![CDATA[Failures detected in:
- test case: coins_tests/updatecoins_simulation_test
- file: coins_tests.cpp
- line: 279
]]></system-err>
</testcase>
<testcase assertions="1" classname="coins_tests" name="ccoins_serialization" time="8.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""ccoins_serialization" fixture ctor"
- file: coins_tests.cpp
- line: 476
]]></error><system-err><![CDATA[Failures detected in:
- test case: coins_tests/ccoins_serialization
- file: coins_tests.cpp
- line: 476
]]></system-err>
</testcase>
<testcase assertions="1" classname="coins_tests" name="ccoins_access" time="8.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""ccoins_access" fixture ctor"
- file: coins_tests.cpp
- line: 621
]]></error><system-err><![CDATA[Failures detected in:
- test case: coins_tests/ccoins_access
- file: coins_tests.cpp
- line: 621
]]></system-err>
</testcase>
<testcase assertions="1" classname="coins_tests" name="ccoins_spend" time="9.1e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""ccoins_spend" fixture ctor"
- file: coins_tests.cpp
- line: 672
]]></error><system-err><![CDATA[Failures detected in:
- test case: coins_tests/ccoins_spend
- file: coins_tests.cpp
- line: 672
]]></system-err>
</testcase>
<testcase assertions="1" classname="coins_tests" name="ccoins_add" time="7.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""ccoins_add" fixture ctor"
- file: coins_tests.cpp
- line: 743
]]></error><system-err><![CDATA[Failures detected in:
- test case: coins_tests/ccoins_add
- file: coins_tests.cpp
- line: 743
]]></system-err>
</testcase>
<testcase assertions="1" classname="coins_tests" name="ccoins_write" time="7.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""ccoins_write" fixture ctor"
- file: coins_tests.cpp
- line: 792
]]></error><system-err><![CDATA[Failures detected in:
- test case: coins_tests/ccoins_write
- file: coins_tests.cpp
- line: 792
]]></system-err>
</testcase>
<testcase assertions="1" classname="compress_tests" name="compress_amounts" time="8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""compress_amounts" fixture ctor"
- file: compress_tests.cpp
- line: 39
]]></error><system-err><![CDATA[Failures detected in:
- test case: compress_tests/compress_amounts
- file: compress_tests.cpp
- line: 39
]]></system-err>
</testcase>
<testcase assertions="1" classname="cn_tests" name="cryptonight_dark_hash" time="7.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""cryptonight_dark_hash" fixture ctor"
- file: cn_tests.cpp
- line: 39
]]></error><system-err><![CDATA[Failures detected in:
- test case: cn_tests/cryptonight_dark_hash
- file: cn_tests.cpp
- line: 39
]]></system-err>
</testcase>
<testcase assertions="1" classname="cn_tests" name="cryptonight_darklite_hash" time="7.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""cryptonight_darklite_hash" fixture ctor"
- file: cn_tests.cpp
- line: 66
]]></error><system-err><![CDATA[Failures detected in:
- test case: cn_tests/cryptonight_darklite_hash
- file: cn_tests.cpp
- line: 66
]]></system-err>
</testcase>
<testcase assertions="1" classname="cn_tests" name="cryptonight_cnfast_hash" time="8.1e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""cryptonight_cnfast_hash" fixture ctor"
- file: cn_tests.cpp
- line: 95
]]></error><system-err><![CDATA[Failures detected in:
- test case: cn_tests/cryptonight_cnfast_hash
- file: cn_tests.cpp
- line: 95
]]></system-err>
</testcase>
<testcase assertions="1" classname="cn_tests" name="cryptonight_cnlite_hash" time="7.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""cryptonight_cnlite_hash" fixture ctor"
- file: cn_tests.cpp
- line: 120
]]></error><system-err><![CDATA[Failures detected in:
- test case: cn_tests/cryptonight_cnlite_hash
- file: cn_tests.cpp
- line: 120
]]></system-err>
</testcase>
<testcase assertions="1" classname="cn_tests" name="cryptonight_turtle_hash" time="7.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""cryptonight_turtle_hash" fixture ctor"
- file: cn_tests.cpp
- line: 139
]]></error><system-err><![CDATA[Failures detected in:
- test case: cn_tests/cryptonight_turtle_hash
- file: cn_tests.cpp
- line: 139
]]></system-err>
</testcase>
<testcase assertions="1" classname="cn_tests" name="cryptonight_turtlelite_hash" time="7.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""cryptonight_turtlelite_hash" fixture ctor"
- file: cn_tests.cpp
- line: 156
]]></error><system-err><![CDATA[Failures detected in:
- test case: cn_tests/cryptonight_turtlelite_hash
- file: cn_tests.cpp
- line: 156
]]></system-err>
</testcase>
<testcase assertions="1" classname="crypto_tests" name="ripemd160_testvectors" time="7.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""ripemd160_testvectors" fixture ctor"
- file: crypto_tests.cpp
- line: 187
]]></error><system-err><![CDATA[Failures detected in:
- test case: crypto_tests/ripemd160_testvectors
- file: crypto_tests.cpp
- line: 187
]]></system-err>
</testcase>
<testcase assertions="1" classname="crypto_tests" name="sha1_testvectors" time="7.2e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""sha1_testvectors" fixture ctor"
- file: crypto_tests.cpp
- line: 203
]]></error><system-err><![CDATA[Failures detected in:
- test case: crypto_tests/sha1_testvectors
- file: crypto_tests.cpp
- line: 203
]]></system-err>
</testcase>
<testcase assertions="1" classname="crypto_tests" name="sha256_testvectors" time="7.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""sha256_testvectors" fixture ctor"
- file: crypto_tests.cpp
- line: 219
]]></error><system-err><![CDATA[Failures detected in:
- test case: crypto_tests/sha256_testvectors
- file: crypto_tests.cpp
- line: 219
]]></system-err>
</testcase>
<testcase assertions="1" classname="crypto_tests" name="sha512_testvectors" time="7.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""sha512_testvectors" fixture ctor"
- file: crypto_tests.cpp
- line: 241
]]></error><system-err><![CDATA[Failures detected in:
- test case: crypto_tests/sha512_testvectors
- file: crypto_tests.cpp
- line: 241
]]></system-err>
</testcase>
<testcase assertions="1" classname="crypto_tests" name="hmac_sha256_testvectors" time="7.2e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""hmac_sha256_testvectors" fixture ctor"
- file: crypto_tests.cpp
- line: 278
]]></error><system-err><![CDATA[Failures detected in:
- test case: crypto_tests/hmac_sha256_testvectors
- file: crypto_tests.cpp
- line: 278
]]></system-err>
</testcase>
<testcase assertions="1" classname="crypto_tests" name="hmac_sha512_testvectors" time="7.2e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""hmac_sha512_testvectors" fixture ctor"
- file: crypto_tests.cpp
- line: 331
]]></error><system-err><![CDATA[Failures detected in:
- test case: crypto_tests/hmac_sha512_testvectors
- file: crypto_tests.cpp
- line: 331
]]></system-err>
</testcase>
<testcase assertions="1" classname="crypto_tests" name="aes_testvectors" time="7.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""aes_testvectors" fixture ctor"
- file: crypto_tests.cpp
- line: 399
]]></error><system-err><![CDATA[Failures detected in:
- test case: crypto_tests/aes_testvectors
- file: crypto_tests.cpp
- line: 399
]]></system-err>
</testcase>
<testcase assertions="1" classname="crypto_tests" name="aes_cbc_testvectors" time="7.2e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""aes_cbc_testvectors" fixture ctor"
- file: crypto_tests.cpp
- line: 410
]]></error><system-err><![CDATA[Failures detected in:
- test case: crypto_tests/aes_cbc_testvectors
- file: crypto_tests.cpp
- line: 410
]]></system-err>
</testcase>
<testcase assertions="1" classname="crypto_tests" name="pbkdf2_hmac_sha512_test" time="7.2e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""pbkdf2_hmac_sha512_test" fixture ctor"
- file: crypto_tests.cpp
- line: 441
]]></error><system-err><![CDATA[Failures detected in:
- test case: crypto_tests/pbkdf2_hmac_sha512_test
- file: crypto_tests.cpp
- line: 441
]]></system-err>
</testcase>
<testcase assertions="1" classname="crypto_tests" name="chacha20_testvector" time="7.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""chacha20_testvector" fixture ctor"
- file: crypto_tests.cpp
- line: 465
]]></error><system-err><![CDATA[Failures detected in:
- test case: crypto_tests/chacha20_testvector
- file: crypto_tests.cpp
- line: 465
]]></system-err>
</testcase>
<testcase assertions="1" classname="crypto_tests" name="poly1305_testvector" time="7.2e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""poly1305_testvector" fixture ctor"
- file: crypto_tests.cpp
- line: 507
]]></error><system-err><![CDATA[Failures detected in:
- test case: crypto_tests/poly1305_testvector
- file: crypto_tests.cpp
- line: 507
]]></system-err>
</testcase>
<testcase assertions="1" classname="crypto_tests" name="chacha20_poly1305_aead_testvector" time="7.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""chacha20_poly1305_aead_testvector" fixture ctor"
- file: crypto_tests.cpp
- line: 669
]]></error><system-err><![CDATA[Failures detected in:
- test case: crypto_tests/chacha20_poly1305_aead_testvector
- file: crypto_tests.cpp
- line: 669
]]></system-err>
</testcase>
<testcase assertions="1" classname="crypto_tests" name="countbits_tests" time="7.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""countbits_tests" fixture ctor"
- file: crypto_tests.cpp
- line: 702
]]></error><system-err><![CDATA[Failures detected in:
- test case: crypto_tests/countbits_tests
- file: crypto_tests.cpp
- line: 702
]]></system-err>
</testcase>
<testcase assertions="1" classname="crypto_tests" name="sha256d64" time="7.2e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""sha256d64" fixture ctor"
- file: crypto_tests.cpp
- line: 724
]]></error><system-err><![CDATA[Failures detected in:
- test case: crypto_tests/sha256d64
- file: crypto_tests.cpp
- line: 724
]]></system-err>
</testcase>
<testcase assertions="100000" classname="cuckoocache_tests" name="test_cuckoocache_no_fakes" time="0.232375">
</testcase>
<testcase assertions="5" classname="cuckoocache_tests" name="cuckoocache_hit_rate_ok" time="0.114496">
</testcase>
<testcase assertions="2" classname="cuckoocache_tests" name="cuckoocache_erase_ok" time="0.034149">
</testcase>
<testcase assertions="2" classname="cuckoocache_tests" name="cuckoocache_erase_parallel_ok" time="0.036607">
</testcase>
<testcase assertions="1311" classname="cuckoocache_tests" name="cuckoocache_generations" time="0.429981">
</testcase>
<testcase assertions="1" classname="denialofservice_tests" name="outbound_slow_chain_eviction" time="0.000176">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""outbound_slow_chain_eviction" fixture ctor"
- file: denialofservice_tests.cpp
- line: 76
]]></error><system-err><![CDATA[Failures detected in:
- test case: denialofservice_tests/outbound_slow_chain_eviction
- file: denialofservice_tests.cpp
- line: 76
]]></system-err>
</testcase>
<testcase assertions="1" classname="denialofservice_tests" name="stale_tip_peer_management" time="6.1e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""stale_tip_peer_management" fixture ctor"
- file: denialofservice_tests.cpp
- line: 147
]]></error><system-err><![CDATA[Failures detected in:
- test case: denialofservice_tests/stale_tip_peer_management
- file: denialofservice_tests.cpp
- line: 147
]]></system-err>
</testcase>
<testcase assertions="1" classname="denialofservice_tests" name="DoS_banning" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""DoS_banning" fixture ctor"
- file: denialofservice_tests.cpp
- line: 219
]]></error><system-err><![CDATA[Failures detected in:
- test case: denialofservice_tests/DoS_banning
- file: denialofservice_tests.cpp
- line: 219
]]></system-err>
</testcase>
<testcase assertions="1" classname="denialofservice_tests" name="DoS_banscore" time="9.9e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""DoS_banscore" fixture ctor"
- file: denialofservice_tests.cpp
- line: 274
]]></error><system-err><![CDATA[Failures detected in:
- test case: denialofservice_tests/DoS_banscore
- file: denialofservice_tests.cpp
- line: 274
]]></system-err>
</testcase>
<testcase assertions="1" classname="denialofservice_tests" name="DoS_bantime" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""DoS_bantime" fixture ctor"
- file: denialofservice_tests.cpp
- line: 321
]]></error><system-err><![CDATA[Failures detected in:
- test case: denialofservice_tests/DoS_bantime
- file: denialofservice_tests.cpp
- line: 321
]]></system-err>
</testcase>
<testcase assertions="1" classname="denialofservice_tests" name="DoS_mapOrphans" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""DoS_mapOrphans" fixture ctor"
- file: denialofservice_tests.cpp
- line: 368
]]></error><system-err><![CDATA[Failures detected in:
- test case: denialofservice_tests/DoS_mapOrphans
- file: denialofservice_tests.cpp
- line: 368
]]></system-err>
</testcase>
<testcase assertions="1" classname="dip0020opcodes_tests" name="negative_valtype_test" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""negative_valtype_test" fixture ctor"
- file: dip0020opcodes_tests.cpp
- line: 89
]]></error><system-err><![CDATA[Failures detected in:
- test case: dip0020opcodes_tests/negative_valtype_test
- file: dip0020opcodes_tests.cpp
- line: 89
]]></system-err>
</testcase>
<testcase assertions="1" classname="dip0020opcodes_tests" name="bitwise_opcodes_test" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""bitwise_opcodes_test" fixture ctor"
- file: dip0020opcodes_tests.cpp
- line: 181
]]></error><system-err><![CDATA[Failures detected in:
- test case: dip0020opcodes_tests/bitwise_opcodes_test
- file: dip0020opcodes_tests.cpp
- line: 181
]]></system-err>
</testcase>
<testcase assertions="1" classname="dip0020opcodes_tests" name="string_opcodes_test" time="6.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""string_opcodes_test" fixture ctor"
- file: dip0020opcodes_tests.cpp
- line: 445
]]></error><system-err><![CDATA[Failures detected in:
- test case: dip0020opcodes_tests/string_opcodes_test
- file: dip0020opcodes_tests.cpp
- line: 445
]]></system-err>
</testcase>
<testcase assertions="1" classname="dip0020opcodes_tests" name="type_conversion_test" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""type_conversion_test" fixture ctor"
- file: dip0020opcodes_tests.cpp
- line: 584
]]></error><system-err><![CDATA[Failures detected in:
- test case: dip0020opcodes_tests/type_conversion_test
- file: dip0020opcodes_tests.cpp
- line: 584
]]></system-err>
</testcase>
<testcase assertions="1" classname="dip0020opcodes_tests" name="div_and_mod_opcode_tests" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""div_and_mod_opcode_tests" fixture ctor"
- file: dip0020opcodes_tests.cpp
- line: 740
]]></error><system-err><![CDATA[Failures detected in:
- test case: dip0020opcodes_tests/div_and_mod_opcode_tests
- file: dip0020opcodes_tests.cpp
- line: 740
]]></system-err>
</testcase>
<testcase assertions="1" classname="dip0020opcodes_tests" name="check_dip0020_inclusion_in_standard_flags" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""check_dip0020_inclusion_in_standard_flags" fixture ctor"
- file: dip0020opcodes_tests.cpp
- line: 789
]]></error><system-err><![CDATA[Failures detected in:
- test case: dip0020opcodes_tests/check_dip0020_inclusion_in_standard_flags
- file: dip0020opcodes_tests.cpp
- line: 789
]]></system-err>
</testcase>
<testcase assertions="1" classname="descriptor_tests" name="descriptor_test" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""descriptor_test" fixture ctor"
- file: descriptor_tests.cpp
- line: 173
]]></error><system-err><![CDATA[Failures detected in:
- test case: descriptor_tests/descriptor_test
- file: descriptor_tests.cpp
- line: 173
]]></system-err>
</testcase>
<testcase assertions="1" classname="evo_dip3_activation_tests" name="dip3_activation" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""dip3_activation" fixture ctor"
- file: evo_deterministicmns_tests.cpp
- line: 246
]]></error><system-err><![CDATA[Failures detected in:
- test case: evo_dip3_activation_tests/dip3_activation
- file: evo_deterministicmns_tests.cpp
- line: 246
]]></system-err>
</testcase>
<testcase assertions="1" classname="evo_dip3_activation_tests" name="dip3_protx" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""dip3_protx" fixture ctor"
- file: evo_deterministicmns_tests.cpp
- line: 277
]]></error><system-err><![CDATA[Failures detected in:
- test case: evo_dip3_activation_tests/dip3_protx
- file: evo_deterministicmns_tests.cpp
- line: 277
]]></system-err>
</testcase>
<testcase assertions="1" classname="evo_dip3_activation_tests" name="dip3_test_mempool_reorg" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""dip3_test_mempool_reorg" fixture ctor"
- file: evo_deterministicmns_tests.cpp
- line: 462
]]></error><system-err><![CDATA[Failures detected in:
- test case: evo_dip3_activation_tests/dip3_test_mempool_reorg
- file: evo_deterministicmns_tests.cpp
- line: 462
]]></system-err>
</testcase>
<testcase assertions="1" classname="evo_dip3_activation_tests" name="dip3_test_mempool_dual_proregtx" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""dip3_test_mempool_dual_proregtx" fixture ctor"
- file: evo_deterministicmns_tests.cpp
- line: 539
]]></error><system-err><![CDATA[Failures detected in:
- test case: evo_dip3_activation_tests/dip3_test_mempool_dual_proregtx
- file: evo_deterministicmns_tests.cpp
- line: 539
]]></system-err>
</testcase>
<testcase assertions="1" classname="evo_dip3_activation_tests" name="dip3_verify_db" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""dip3_verify_db" fixture ctor"
- file: evo_deterministicmns_tests.cpp
- line: 596
]]></error><system-err><![CDATA[Failures detected in:
- test case: evo_dip3_activation_tests/dip3_verify_db
- file: evo_deterministicmns_tests.cpp
- line: 596
]]></system-err>
</testcase>
<testcase assertions="1" classname="evo_simplifiedmns_tests" name="simplifiedmns_merkleroots" time="0.000278">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""simplifiedmns_merkleroots" fixture ctor"
- file: evo_simplifiedmns_tests.cpp
- line: 16
]]></error><system-err><![CDATA[Failures detected in:
- test case: evo_simplifiedmns_tests/simplifiedmns_merkleroots
- file: evo_simplifiedmns_tests.cpp
- line: 16
]]></system-err>
</testcase>
<testcase assertions="1" classname="flatfile_tests" name="flatfile_filename" time="7.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""flatfile_filename" fixture ctor"
- file: flatfile_tests.cpp
- line: 12
]]></error><system-err><![CDATA[Failures detected in:
- test case: flatfile_tests/flatfile_filename
- file: flatfile_tests.cpp
- line: 12
]]></system-err>
</testcase>
<testcase assertions="1" classname="flatfile_tests" name="flatfile_open" time="6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""flatfile_open" fixture ctor"
- file: flatfile_tests.cpp
- line: 25
]]></error><system-err><![CDATA[Failures detected in:
- test case: flatfile_tests/flatfile_open
- file: flatfile_tests.cpp
- line: 25
]]></system-err>
</testcase>
<testcase assertions="1" classname="flatfile_tests" name="flatfile_allocate" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""flatfile_allocate" fixture ctor"
- file: flatfile_tests.cpp
- line: 86
]]></error><system-err><![CDATA[Failures detected in:
- test case: flatfile_tests/flatfile_allocate
- file: flatfile_tests.cpp
- line: 86
]]></system-err>
</testcase>
<testcase assertions="1" classname="flatfile_tests" name="flatfile_flush" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""flatfile_flush" fixture ctor"
- file: flatfile_tests.cpp
- line: 106
]]></error><system-err><![CDATA[Failures detected in:
- test case: flatfile_tests/flatfile_flush
- file: flatfile_tests.cpp
- line: 106
]]></system-err>
</testcase>
<testcase assertions="1" classname="fs_tests" name="fsbridge_fstream" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""fsbridge_fstream" fixture ctor"
- file: fs_tests.cpp
- line: 12
]]></error><system-err><![CDATA[Failures detected in:
- test case: fs_tests/fsbridge_fstream
- file: fs_tests.cpp
- line: 12
]]></system-err>
</testcase>
<testcase assertions="1" classname="getarg_tests" name="boolarg" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""boolarg" fixture ctor"
- file: getarg_tests.cpp
- line: 44
]]></error><system-err><![CDATA[Failures detected in:
- test case: getarg_tests/boolarg
- file: getarg_tests.cpp
- line: 44
]]></system-err>
</testcase>
<testcase assertions="1" classname="getarg_tests" name="stringarg" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""stringarg" fixture ctor"
- file: getarg_tests.cpp
- line: 98
]]></error><system-err><![CDATA[Failures detected in:
- test case: getarg_tests/stringarg
- file: getarg_tests.cpp
- line: 98
]]></system-err>
</testcase>
<testcase assertions="1" classname="getarg_tests" name="intarg" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""intarg" fixture ctor"
- file: getarg_tests.cpp
- line: 125
]]></error><system-err><![CDATA[Failures detected in:
- test case: getarg_tests/intarg
- file: getarg_tests.cpp
- line: 125
]]></system-err>
</testcase>
<testcase assertions="1" classname="getarg_tests" name="doubledash" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""doubledash" fixture ctor"
- file: getarg_tests.cpp
- line: 147
]]></error><system-err><![CDATA[Failures detected in:
- test case: getarg_tests/doubledash
- file: getarg_tests.cpp
- line: 147
]]></system-err>
</testcase>
<testcase assertions="1" classname="getarg_tests" name="boolargno" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""boolargno" fixture ctor"
- file: getarg_tests.cpp
- line: 160
]]></error><system-err><![CDATA[Failures detected in:
- test case: getarg_tests/boolargno
- file: getarg_tests.cpp
- line: 160
]]></system-err>
</testcase>
<testcase assertions="1" classname="governance_validators_tests" name="valid_proposals_test" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""valid_proposals_test" fixture ctor"
- file: governance_validators_tests.cpp
- line: 38
]]></error><system-err><![CDATA[Failures detected in:
- test case: governance_validators_tests/valid_proposals_test
- file: governance_validators_tests.cpp
- line: 38
]]></system-err>
</testcase>
<testcase assertions="1" classname="governance_validators_tests" name="invalid_proposals_test" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""invalid_proposals_test" fixture ctor"
- file: governance_validators_tests.cpp
- line: 66
]]></error><system-err><![CDATA[Failures detected in:
- test case: governance_validators_tests/invalid_proposals_test
- file: governance_validators_tests.cpp
- line: 66
]]></system-err>
</testcase>
<testcase assertions="1" classname="hash_tests" name="murmurhash3" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""murmurhash3" fixture ctor"
- file: hash_tests.cpp
- line: 15
]]></error><system-err><![CDATA[Failures detected in:
- test case: hash_tests/murmurhash3
- file: hash_tests.cpp
- line: 15
]]></system-err>
</testcase>
<testcase assertions="1" classname="hash_tests" name="siphash" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""siphash" fixture ctor"
- file: hash_tests.cpp
- line: 80
]]></error><system-err><![CDATA[Failures detected in:
- test case: hash_tests/siphash
- file: hash_tests.cpp
- line: 80
]]></system-err>
</testcase>
<testcase assertions="1" classname="key_io_tests" name="key_io_valid_parse" time="0.000212">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""key_io_valid_parse" fixture ctor"
- file: key_io_tests.cpp
- line: 24
]]></error><system-err><![CDATA[Failures detected in:
- test case: key_io_tests/key_io_valid_parse
- file: key_io_tests.cpp
- line: 24
]]></system-err>
</testcase>
<testcase assertions="1" classname="key_io_tests" name="key_io_valid_gen" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""key_io_valid_gen" fixture ctor"
- file: key_io_tests.cpp
- line: 85
]]></error><system-err><![CDATA[Failures detected in:
- test case: key_io_tests/key_io_valid_gen
- file: key_io_tests.cpp
- line: 85
]]></system-err>
</testcase>
<testcase assertions="1" classname="key_io_tests" name="key_io_invalid" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""key_io_invalid" fixture ctor"
- file: key_io_tests.cpp
- line: 123
]]></error><system-err><![CDATA[Failures detected in:
- test case: key_io_tests/key_io_invalid
- file: key_io_tests.cpp
- line: 123
]]></system-err>
</testcase>
<testcase assertions="1" classname="key_tests" name="key_test1" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""key_test1" fixture ctor"
- file: key_tests.cpp
- line: 33
]]></error><system-err><![CDATA[Failures detected in:
- test case: key_tests/key_test1
- file: key_tests.cpp
- line: 33
]]></system-err>
</testcase>
<testcase assertions="1" classname="limitedmap_tests" name="limitedmap_test" time="0.000109">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""limitedmap_test" fixture ctor"
- file: limitedmap_tests.cpp
- line: 13
]]></error><system-err><![CDATA[Failures detected in:
- test case: limitedmap_tests/limitedmap_test
- file: limitedmap_tests.cpp
- line: 13
]]></system-err>
</testcase>
<testcase assertions="1" classname="dbwrapper_tests" name="dbwrapper" time="0.000162">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""dbwrapper" fixture ctor"
- file: dbwrapper_tests.cpp
- line: 26
]]></error><system-err><![CDATA[Failures detected in:
- test case: dbwrapper_tests/dbwrapper
- file: dbwrapper_tests.cpp
- line: 26
]]></system-err>
</testcase>
<testcase assertions="1" classname="dbwrapper_tests" name="dbwrapper_batch" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""dbwrapper_batch" fixture ctor"
- file: dbwrapper_tests.cpp
- line: 46
]]></error><system-err><![CDATA[Failures detected in:
- test case: dbwrapper_tests/dbwrapper_batch
- file: dbwrapper_tests.cpp
- line: 46
]]></system-err>
</testcase>
<testcase assertions="1" classname="dbwrapper_tests" name="dbwrapper_iterator" time="8.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""dbwrapper_iterator" fixture ctor"
- file: dbwrapper_tests.cpp
- line: 82
]]></error><system-err><![CDATA[Failures detected in:
- test case: dbwrapper_tests/dbwrapper_iterator
- file: dbwrapper_tests.cpp
- line: 82
]]></system-err>
</testcase>
<testcase assertions="1" classname="dbwrapper_tests" name="existing_data_no_obfuscate" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""existing_data_no_obfuscate" fixture ctor"
- file: dbwrapper_tests.cpp
- line: 123
]]></error><system-err><![CDATA[Failures detected in:
- test case: dbwrapper_tests/existing_data_no_obfuscate
- file: dbwrapper_tests.cpp
- line: 123
]]></system-err>
</testcase>
<testcase assertions="1" classname="dbwrapper_tests" name="existing_data_reindex" time="6.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""existing_data_reindex" fixture ctor"
- file: dbwrapper_tests.cpp
- line: 164
]]></error><system-err><![CDATA[Failures detected in:
- test case: dbwrapper_tests/existing_data_reindex
- file: dbwrapper_tests.cpp
- line: 164
]]></system-err>
</testcase>
<testcase assertions="1" classname="dbwrapper_tests" name="iterator_ordering" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""iterator_ordering" fixture ctor"
- file: dbwrapper_tests.cpp
- line: 200
]]></error><system-err><![CDATA[Failures detected in:
- test case: dbwrapper_tests/iterator_ordering
- file: dbwrapper_tests.cpp
- line: 200
]]></system-err>
</testcase>
<testcase assertions="1" classname="dbwrapper_tests" name="iterator_string_ordering" time="5.9e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""iterator_string_ordering" fixture ctor"
- file: dbwrapper_tests.cpp
- line: 278
]]></error><system-err><![CDATA[Failures detected in:
- test case: dbwrapper_tests/iterator_string_ordering
- file: dbwrapper_tests.cpp
- line: 278
]]></system-err>
</testcase>
<testcase assertions="1" classname="main_tests" name="test_combiner_all" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_combiner_all" fixture ctor"
- file: main_tests.cpp
- line: 21
]]></error><system-err><![CDATA[Failures detected in:
- test case: main_tests/test_combiner_all
- file: main_tests.cpp
- line: 21
]]></system-err>
</testcase>
<testcase assertions="1" classname="mempool_tests" name="MempoolRemoveTest" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""MempoolRemoveTest" fixture ctor"
- file: mempool_tests.cpp
- line: 19
]]></error><system-err><![CDATA[Failures detected in:
- test case: mempool_tests/MempoolRemoveTest
- file: mempool_tests.cpp
- line: 19
]]></system-err>
</testcase>
<testcase assertions="1" classname="mempool_tests" name="MempoolIndexingTest" time="0.000304">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""MempoolIndexingTest" fixture ctor"
- file: mempool_tests.cpp
- line: 122
]]></error><system-err><![CDATA[Failures detected in:
- test case: mempool_tests/MempoolIndexingTest
- file: mempool_tests.cpp
- line: 122
]]></system-err>
</testcase>
<testcase assertions="1" classname="mempool_tests" name="MempoolAncestorIndexingTest" time="5.9e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""MempoolAncestorIndexingTest" fixture ctor"
- file: mempool_tests.cpp
- line: 295
]]></error><system-err><![CDATA[Failures detected in:
- test case: mempool_tests/MempoolAncestorIndexingTest
- file: mempool_tests.cpp
- line: 295
]]></system-err>
</testcase>
<testcase assertions="1" classname="mempool_tests" name="MempoolSizeLimitTest" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""MempoolSizeLimitTest" fixture ctor"
- file: mempool_tests.cpp
- line: 424
]]></error><system-err><![CDATA[Failures detected in:
- test case: mempool_tests/MempoolSizeLimitTest
- file: mempool_tests.cpp
- line: 424
]]></system-err>
</testcase>
<testcase assertions="1" classname="mempool_tests" name="MempoolAncestryTests" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""MempoolAncestryTests" fixture ctor"
- file: mempool_tests.cpp
- line: 598
]]></error><system-err><![CDATA[Failures detected in:
- test case: mempool_tests/MempoolAncestryTests
- file: mempool_tests.cpp
- line: 598
]]></system-err>
</testcase>
<testcase assertions="1" classname="merkle_tests" name="merkle_test" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""merkle_test" fixture ctor"
- file: merkle_tests.cpp
- line: 183
]]></error><system-err><![CDATA[Failures detected in:
- test case: merkle_tests/merkle_test
- file: merkle_tests.cpp
- line: 183
]]></system-err>
</testcase>
<testcase assertions="1" classname="merkleblock_tests" name="merkleblock_construct_from_txids_found" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""merkleblock_construct_from_txids_found" fixture ctor"
- file: merkleblock_tests.cpp
- line: 18
]]></error><system-err><![CDATA[Failures detected in:
- test case: merkleblock_tests/merkleblock_construct_from_txids_found
- file: merkleblock_tests.cpp
- line: 18
]]></system-err>
</testcase>
<testcase assertions="1" classname="merkleblock_tests" name="merkleblock_construct_from_txids_not_found" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""merkleblock_construct_from_txids_not_found" fixture ctor"
- file: merkleblock_tests.cpp
- line: 59
]]></error><system-err><![CDATA[Failures detected in:
- test case: merkleblock_tests/merkleblock_construct_from_txids_not_found
- file: merkleblock_tests.cpp
- line: 59
]]></system-err>
</testcase>
<testcase assertions="1" classname="miner_tests" name="CreateNewBlock_validity" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""CreateNewBlock_validity" fixture ctor"
- file: miner_tests.cpp
- line: 203
]]></error><system-err><![CDATA[Failures detected in:
- test case: miner_tests/CreateNewBlock_validity
- file: miner_tests.cpp
- line: 203
]]></system-err>
</testcase>
<testcase assertions="1" classname="multisig_tests" name="multisig_verify" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""multisig_verify" fixture ctor"
- file: multisig_tests.cpp
- line: 38
]]></error><system-err><![CDATA[Failures detected in:
- test case: multisig_tests/multisig_verify
- file: multisig_tests.cpp
- line: 38
]]></system-err>
</testcase>
<testcase assertions="1" classname="multisig_tests" name="multisig_IsStandard" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""multisig_IsStandard" fixture ctor"
- file: multisig_tests.cpp
- line: 138
]]></error><system-err><![CDATA[Failures detected in:
- test case: multisig_tests/multisig_IsStandard
- file: multisig_tests.cpp
- line: 138
]]></system-err>
</testcase>
<testcase assertions="1" classname="multisig_tests" name="multisig_Sign" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""multisig_Sign" fixture ctor"
- file: multisig_tests.cpp
- line: 174
]]></error><system-err><![CDATA[Failures detected in:
- test case: multisig_tests/multisig_Sign
- file: multisig_tests.cpp
- line: 174
]]></system-err>
</testcase>
<testcase assertions="1" classname="net_tests" name="cnode_listen_port" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""cnode_listen_port" fixture ctor"
- file: net_tests.cpp
- line: 80
]]></error><system-err><![CDATA[Failures detected in:
- test case: net_tests/cnode_listen_port
- file: net_tests.cpp
- line: 80
]]></system-err>
</testcase>
<testcase assertions="1" classname="net_tests" name="caddrdb_read" time="5.9e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""caddrdb_read" fixture ctor"
- file: net_tests.cpp
- line: 92
]]></error><system-err><![CDATA[Failures detected in:
- test case: net_tests/caddrdb_read
- file: net_tests.cpp
- line: 92
]]></system-err>
</testcase>
<testcase assertions="1" classname="net_tests" name="caddrdb_read_corrupted" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""caddrdb_read_corrupted" fixture ctor"
- file: net_tests.cpp
- line: 138
]]></error><system-err><![CDATA[Failures detected in:
- test case: net_tests/caddrdb_read_corrupted
- file: net_tests.cpp
- line: 138
]]></system-err>
</testcase>
<testcase assertions="1" classname="net_tests" name="cnode_simple_test" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""cnode_simple_test" fixture ctor"
- file: net_tests.cpp
- line: 170
]]></error><system-err><![CDATA[Failures detected in:
- test case: net_tests/cnode_simple_test
- file: net_tests.cpp
- line: 170
]]></system-err>
</testcase>
<testcase assertions="1" classname="net_tests" name="PoissonNextSend" time="5.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""PoissonNextSend" fixture ctor"
- file: net_tests.cpp
- line: 194
]]></error><system-err><![CDATA[Failures detected in:
- test case: net_tests/PoissonNextSend
- file: net_tests.cpp
- line: 194
]]></system-err>
</testcase>
<testcase assertions="1" classname="net_tests" name="cnetaddr_basic" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""cnetaddr_basic" fixture ctor"
- file: net_tests.cpp
- line: 208
]]></error><system-err><![CDATA[Failures detected in:
- test case: net_tests/cnetaddr_basic
- file: net_tests.cpp
- line: 208
]]></system-err>
</testcase>
<testcase assertions="1" classname="net_tests" name="cnetaddr_serialize" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""cnetaddr_serialize" fixture ctor"
- file: net_tests.cpp
- line: 269
]]></error><system-err><![CDATA[Failures detected in:
- test case: net_tests/cnetaddr_serialize
- file: net_tests.cpp
- line: 269
]]></system-err>
</testcase>
<testcase assertions="1" classname="net_tests" name="ipv4_peer_with_ipv6_addrMe_test" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""ipv4_peer_with_ipv6_addrMe_test" fixture ctor"
- file: net_tests.cpp
- line: 281
]]></error><system-err><![CDATA[Failures detected in:
- test case: net_tests/ipv4_peer_with_ipv6_addrMe_test
- file: net_tests.cpp
- line: 281
]]></system-err>
</testcase>
<testcase assertions="1" classname="netbase_tests" name="netbase_networks" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""netbase_networks" fixture ctor"
- file: netbase_tests.cpp
- line: 38
]]></error><system-err><![CDATA[Failures detected in:
- test case: netbase_tests/netbase_networks
- file: netbase_tests.cpp
- line: 38
]]></system-err>
</testcase>
<testcase assertions="1" classname="netbase_tests" name="netbase_properties" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""netbase_properties" fixture ctor"
- file: netbase_tests.cpp
- line: 49
]]></error><system-err><![CDATA[Failures detected in:
- test case: netbase_tests/netbase_properties
- file: netbase_tests.cpp
- line: 49
]]></system-err>
</testcase>
<testcase assertions="1" classname="netbase_tests" name="netbase_splithost" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""netbase_splithost" fixture ctor"
- file: netbase_tests.cpp
- line: 86
]]></error><system-err><![CDATA[Failures detected in:
- test case: netbase_tests/netbase_splithost
- file: netbase_tests.cpp
- line: 86
]]></system-err>
</testcase>
<testcase assertions="1" classname="netbase_tests" name="netbase_lookupnumeric" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""netbase_lookupnumeric" fixture ctor"
- file: netbase_tests.cpp
- line: 111
]]></error><system-err><![CDATA[Failures detected in:
- test case: netbase_tests/netbase_lookupnumeric
- file: netbase_tests.cpp
- line: 111
]]></system-err>
</testcase>
<testcase assertions="1" classname="netbase_tests" name="onioncat_test" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""onioncat_test" fixture ctor"
- file: netbase_tests.cpp
- line: 127
]]></error><system-err><![CDATA[Failures detected in:
- test case: netbase_tests/onioncat_test
- file: netbase_tests.cpp
- line: 127
]]></system-err>
</testcase>
<testcase assertions="1" classname="netbase_tests" name="embedded_test" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""embedded_test" fixture ctor"
- file: netbase_tests.cpp
- line: 140
]]></error><system-err><![CDATA[Failures detected in:
- test case: netbase_tests/embedded_test
- file: netbase_tests.cpp
- line: 140
]]></system-err>
</testcase>
<testcase assertions="1" classname="netbase_tests" name="subnet_test" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""subnet_test" fixture ctor"
- file: netbase_tests.cpp
- line: 148
]]></error><system-err><![CDATA[Failures detected in:
- test case: netbase_tests/subnet_test
- file: netbase_tests.cpp
- line: 148
]]></system-err>
</testcase>
<testcase assertions="1" classname="netbase_tests" name="netbase_getgroup" time="7.2e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""netbase_getgroup" fixture ctor"
- file: netbase_tests.cpp
- line: 307
]]></error><system-err><![CDATA[Failures detected in:
- test case: netbase_tests/netbase_getgroup
- file: netbase_tests.cpp
- line: 307
]]></system-err>
</testcase>
<testcase assertions="1" classname="pmt_tests" name="pmt_test1" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""pmt_test1" fixture ctor"
- file: pmt_tests.cpp
- line: 31
]]></error><system-err><![CDATA[Failures detected in:
- test case: pmt_tests/pmt_test1
- file: pmt_tests.cpp
- line: 31
]]></system-err>
</testcase>
<testcase assertions="1" classname="pmt_tests" name="pmt_malleability" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""pmt_malleability" fixture ctor"
- file: pmt_tests.cpp
- line: 108
]]></error><system-err><![CDATA[Failures detected in:
- test case: pmt_tests/pmt_malleability
- file: pmt_tests.cpp
- line: 108
]]></system-err>
</testcase>
<testcase assertions="1" classname="policyestimator_tests" name="BlockPolicyEstimates" time="6.1e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""BlockPolicyEstimates" fixture ctor"
- file: policyestimator_tests.cpp
- line: 15
]]></error><system-err><![CDATA[Failures detected in:
- test case: policyestimator_tests/BlockPolicyEstimates
- file: policyestimator_tests.cpp
- line: 15
]]></system-err>
</testcase>
<testcase assertions="1" classname="pow_tests" name="get_next_work" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""get_next_work" fixture ctor"
- file: pow_tests.cpp
- line: 27
]]></error><system-err><![CDATA[Failures detected in:
- test case: pow_tests/get_next_work
- file: pow_tests.cpp
- line: 27
]]></system-err>
</testcase>
<testcase assertions="1" classname="pow_tests" name="GetBlockProofEquivalentTime_test" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""GetBlockProofEquivalentTime_test" fixture ctor"
- file: pow_tests.cpp
- line: 125
]]></error><system-err><![CDATA[Failures detected in:
- test case: pow_tests/GetBlockProofEquivalentTime_test
- file: pow_tests.cpp
- line: 125
]]></system-err>
</testcase>
<testcase assertions="1" classname="prevector_tests" name="PrevectorTestInt" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""PrevectorTestInt" fixture ctor"
- file: prevector_tests.cpp
- line: 217
]]></error><system-err><![CDATA[Failures detected in:
- test case: prevector_tests/PrevectorTestInt
- file: prevector_tests.cpp
- line: 217
]]></system-err>
</testcase>
<testcase assertions="1" classname="raii_event_tests" name="raii_event_creation" time="5.9e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""raii_event_creation" fixture ctor"
- file: raii_event_tests.cpp
- line: 41
]]></error><system-err><![CDATA[Failures detected in:
- test case: raii_event_tests/raii_event_creation
- file: raii_event_tests.cpp
- line: 41
]]></system-err>
</testcase>
<testcase assertions="1" classname="raii_event_tests" name="raii_event_order" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""raii_event_order" fixture ctor"
- file: raii_event_tests.cpp
- line: 70
]]></error><system-err><![CDATA[Failures detected in:
- test case: raii_event_tests/raii_event_order
- file: raii_event_tests.cpp
- line: 70
]]></system-err>
</testcase>
<testcase assertions="1" classname="random_tests" name="osrandom_tests" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""osrandom_tests" fixture ctor"
- file: random_tests.cpp
- line: 16
]]></error><system-err><![CDATA[Failures detected in:
- test case: random_tests/osrandom_tests
- file: random_tests.cpp
- line: 16
]]></system-err>
</testcase>
<testcase assertions="1" classname="random_tests" name="fastrandom_tests" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""fastrandom_tests" fixture ctor"
- file: random_tests.cpp
- line: 21
]]></error><system-err><![CDATA[Failures detected in:
- test case: random_tests/fastrandom_tests
- file: random_tests.cpp
- line: 21
]]></system-err>
</testcase>
<testcase assertions="1" classname="random_tests" name="fastrandom_randbits" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""fastrandom_randbits" fixture ctor"
- file: random_tests.cpp
- line: 65
]]></error><system-err><![CDATA[Failures detected in:
- test case: random_tests/fastrandom_randbits
- file: random_tests.cpp
- line: 65
]]></system-err>
</testcase>
<testcase assertions="1" classname="random_tests" name="stdrandom_test" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""stdrandom_test" fixture ctor"
- file: random_tests.cpp
- line: 81
]]></error><system-err><![CDATA[Failures detected in:
- test case: random_tests/stdrandom_test
- file: random_tests.cpp
- line: 81
]]></system-err>
</testcase>
<testcase assertions="1" classname="random_tests" name="shuffle_stat_test" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""shuffle_stat_test" fixture ctor"
- file: random_tests.cpp
- line: 103
]]></error><system-err><![CDATA[Failures detected in:
- test case: random_tests/shuffle_stat_test
- file: random_tests.cpp
- line: 103
]]></system-err>
</testcase>
<testcase assertions="12" classname="ref_tests" name="ref_test" time="0.000379">
</testcase>
<testcase assertions="1" classname="ratecheck_tests" name="ratecheck_test" time="8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""ratecheck_test" fixture ctor"
- file: ratecheck_tests.cpp
- line: 12
]]></error><system-err><![CDATA[Failures detected in:
- test case: ratecheck_tests/ratecheck_test
- file: ratecheck_tests.cpp
- line: 12
]]></system-err>
</testcase>
<testcase assertions="3" classname="reverselock_tests" name="reverselock_basics" time="4.5e-05">
</testcase>
<testcase assertions="4" classname="reverselock_tests" name="reverselock_multiple" time="4.2e-05">
</testcase>
<testcase assertions="9" classname="reverselock_tests" name="reverselock_errors" time="7.9e-05">
</testcase>
<testcase assertions="1" classname="rpc_tests" name="rpc_rawparams" time="0.000274">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""rpc_rawparams" fixture ctor"
- file: rpc_tests.cpp
- line: 54
]]></error><system-err><![CDATA[Failures detected in:
- test case: rpc_tests/rpc_rawparams
- file: rpc_tests.cpp
- line: 54
]]></system-err>
</testcase>
<testcase assertions="1" classname="rpc_tests" name="rpc_togglenetwork" time="8.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""rpc_togglenetwork" fixture ctor"
- file: rpc_tests.cpp
- line: 87
]]></error><system-err><![CDATA[Failures detected in:
- test case: rpc_tests/rpc_togglenetwork
- file: rpc_tests.cpp
- line: 87
]]></system-err>
</testcase>
<testcase assertions="1" classname="rpc_tests" name="rpc_rawsign" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""rpc_rawsign" fixture ctor"
- file: rpc_tests.cpp
- line: 109
]]></error><system-err><![CDATA[Failures detected in:
- test case: rpc_tests/rpc_rawsign
- file: rpc_tests.cpp
- line: 109
]]></system-err>
</testcase>
<testcase assertions="1" classname="rpc_tests" name="rpc_createraw_op_return" time="7.9e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""rpc_createraw_op_return" fixture ctor"
- file: rpc_tests.cpp
- line: 128
]]></error><system-err><![CDATA[Failures detected in:
- test case: rpc_tests/rpc_createraw_op_return
- file: rpc_tests.cpp
- line: 128
]]></system-err>
</testcase>
<testcase assertions="1" classname="rpc_tests" name="rpc_format_monetary_values" time="6.2e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""rpc_format_monetary_values" fixture ctor"
- file: rpc_tests.cpp
- line: 146
]]></error><system-err><![CDATA[Failures detected in:
- test case: rpc_tests/rpc_format_monetary_values
- file: rpc_tests.cpp
- line: 146
]]></system-err>
</testcase>
<testcase assertions="1" classname="rpc_tests" name="rpc_parse_monetary_values" time="6.1e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""rpc_parse_monetary_values" fixture ctor"
- file: rpc_tests.cpp
- line: 188
]]></error><system-err><![CDATA[Failures detected in:
- test case: rpc_tests/rpc_parse_monetary_values
- file: rpc_tests.cpp
- line: 188
]]></system-err>
</testcase>
<testcase assertions="1" classname="rpc_tests" name="json_parse_errors" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""json_parse_errors" fixture ctor"
- file: rpc_tests.cpp
- line: 221
]]></error><system-err><![CDATA[Failures detected in:
- test case: rpc_tests/json_parse_errors
- file: rpc_tests.cpp
- line: 221
]]></system-err>
</testcase>
<testcase assertions="1" classname="rpc_tests" name="rpc_ban" time="6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""rpc_ban" fixture ctor"
- file: rpc_tests.cpp
- line: 242
]]></error><system-err><![CDATA[Failures detected in:
- test case: rpc_tests/rpc_ban
- file: rpc_tests.cpp
- line: 242
]]></system-err>
</testcase>
<testcase assertions="1" classname="rpc_tests" name="rpc_convert_values_generatetoaddress" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""rpc_convert_values_generatetoaddress" fixture ctor"
- file: rpc_tests.cpp
- line: 326
]]></error><system-err><![CDATA[Failures detected in:
- test case: rpc_tests/rpc_convert_values_generatetoaddress
- file: rpc_tests.cpp
- line: 326
]]></system-err>
</testcase>
<testcase assertions="1" classname="sanity_tests" name="basic_sanity" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""basic_sanity" fixture ctor"
- file: sanity_tests.cpp
- line: 14
]]></error><system-err><![CDATA[Failures detected in:
- test case: sanity_tests/basic_sanity
- file: sanity_tests.cpp
- line: 14
]]></system-err>
</testcase>
<testcase assertions="15" classname="scheduler_tests" name="manythreads" time="0.006904">
</testcase>
<testcase assertions="202" classname="scheduler_tests" name="singlethreadedscheduler_ordered" time="0.005114">
<system-out><![CDATA[ == check  has passed

 == 



counter2++



counter1++i]]></system-out>
</testcase>
<testcase assertions="4" classname="scheduler_tests" name="mockforward" time="0.001252">
</testcase>
<testcase assertions="1" classname="script_p2sh_tests" name="sign" time="0.000132">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""sign" fixture ctor"
- file: script_p2sh_tests.cpp
- line: 52
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_p2sh_tests/sign
- file: script_p2sh_tests.cpp
- line: 52
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_p2sh_tests" name="norecurse" time="9.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""norecurse" fixture ctor"
- file: script_p2sh_tests.cpp
- line: 125
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_p2sh_tests/norecurse
- file: script_p2sh_tests.cpp
- line: 125
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_p2sh_tests" name="set" time="0.000149">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""set" fixture ctor"
- file: script_p2sh_tests.cpp
- line: 152
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_p2sh_tests/set
- file: script_p2sh_tests.cpp
- line: 152
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_p2sh_tests" name="is" time="8.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""is" fixture ctor"
- file: script_p2sh_tests.cpp
- line: 206
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_p2sh_tests/is
- file: script_p2sh_tests.cpp
- line: 206
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_p2sh_tests" name="switchover" time="0.000102">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""switchover" fixture ctor"
- file: script_p2sh_tests.cpp
- line: 237
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_p2sh_tests/switchover
- file: script_p2sh_tests.cpp
- line: 237
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_p2sh_tests" name="AreInputsStandard" time="9.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""AreInputsStandard" fixture ctor"
- file: script_p2sh_tests.cpp
- line: 257
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_p2sh_tests/AreInputsStandard
- file: script_p2sh_tests.cpp
- line: 257
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_p2pk_tests" name="IsPayToPublicKey" time="9.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""IsPayToPublicKey" fixture ctor"
- file: script_p2pk_tests.cpp
- line: 13
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_p2pk_tests/IsPayToPublicKey
- file: script_p2pk_tests.cpp
- line: 13
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_p2pkh_tests" name="IsPayToPublicKeyHash" time="9.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""IsPayToPublicKeyHash" fixture ctor"
- file: script_p2pkh_tests.cpp
- line: 12
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_p2pkh_tests/IsPayToPublicKeyHash
- file: script_p2pkh_tests.cpp
- line: 12
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_tests" name="script_build" time="9.9e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""script_build" fixture ctor"
- file: script_tests.cpp
- line: 445
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_tests/script_build
- file: script_tests.cpp
- line: 445
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_tests" name="script_json_test" time="9.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""script_json_test" fixture ctor"
- file: script_tests.cpp
- line: 917
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_tests/script_json_test
- file: script_tests.cpp
- line: 917
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_tests" name="script_PushData" time="9.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""script_PushData" fixture ctor"
- file: script_tests.cpp
- line: 947
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_tests/script_PushData
- file: script_tests.cpp
- line: 947
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_tests" name="script_CHECKMULTISIG12" time="9.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""script_CHECKMULTISIG12" fixture ctor"
- file: script_tests.cpp
- line: 1009
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_tests/script_CHECKMULTISIG12
- file: script_tests.cpp
- line: 1009
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_tests" name="script_CHECKMULTISIG23" time="9.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""script_CHECKMULTISIG23" fixture ctor"
- file: script_tests.cpp
- line: 1039
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_tests/script_CHECKMULTISIG23
- file: script_tests.cpp
- line: 1039
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_tests" name="script_combineSigs" time="0.000102">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""script_combineSigs" fixture ctor"
- file: script_tests.cpp
- line: 1118
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_tests/script_combineSigs
- file: script_tests.cpp
- line: 1118
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_tests" name="script_standard_push" time="0.000103">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""script_standard_push" fixture ctor"
- file: script_tests.cpp
- line: 1232
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_tests/script_standard_push
- file: script_tests.cpp
- line: 1232
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_tests" name="script_IsPushOnly_on_invalid_scripts" time="0.000102">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""script_IsPushOnly_on_invalid_scripts" fixture ctor"
- file: script_tests.cpp
- line: 1253
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_tests/script_IsPushOnly_on_invalid_scripts
- file: script_tests.cpp
- line: 1253
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_tests" name="script_GetScriptAsm" time="9.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""script_GetScriptAsm" fixture ctor"
- file: script_tests.cpp
- line: 1264
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_tests/script_GetScriptAsm
- file: script_tests.cpp
- line: 1264
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_tests" name="script_FindAndDelete" time="0.000106">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""script_FindAndDelete" fixture ctor"
- file: script_tests.cpp
- line: 1302
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_tests/script_FindAndDelete
- file: script_tests.cpp
- line: 1302
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_tests" name="script_can_append_self" time="0.000135">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""script_can_append_self" fixture ctor"
- file: script_tests.cpp
- line: 1411
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_tests/script_can_append_self
- file: script_tests.cpp
- line: 1411
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_standard_tests" name="script_standard_Solver_success" time="0.000133">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""script_standard_Solver_success" fixture ctor"
- file: script_standard_tests.cpp
- line: 16
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_standard_tests/script_standard_Solver_success
- file: script_standard_tests.cpp
- line: 16
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_standard_tests" name="script_standard_Solver_failure" time="0.000128">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""script_standard_Solver_failure" fixture ctor"
- file: script_standard_tests.cpp
- line: 93
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_standard_tests/script_standard_Solver_failure
- file: script_standard_tests.cpp
- line: 93
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_standard_tests" name="script_standard_ExtractDestination" time="8.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""script_standard_ExtractDestination" fixture ctor"
- file: script_standard_tests.cpp
- line: 144
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_standard_tests/script_standard_ExtractDestination
- file: script_standard_tests.cpp
- line: 144
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_standard_tests" name="script_standard_ExtractDestinations" time="8.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""script_standard_ExtractDestinations" fixture ctor"
- file: script_standard_tests.cpp
- line: 187
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_standard_tests/script_standard_ExtractDestinations
- file: script_standard_tests.cpp
- line: 187
]]></system-err>
</testcase>
<testcase assertions="1" classname="script_standard_tests" name="script_standard_GetScriptFor_" time="0.000107">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""script_standard_GetScriptFor_" fixture ctor"
- file: script_standard_tests.cpp
- line: 253
]]></error><system-err><![CDATA[Failures detected in:
- test case: script_standard_tests/script_standard_GetScriptFor_
- file: script_standard_tests.cpp
- line: 253
]]></system-err>
</testcase>
<testcase assertions="1" classname="scriptnum_tests" name="creation" time="0.000156">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""creation" fixture ctor"
- file: scriptnum_tests.cpp
- line: 165
]]></error><system-err><![CDATA[Failures detected in:
- test case: scriptnum_tests/creation
- file: scriptnum_tests.cpp
- line: 165
]]></system-err>
</testcase>
<testcase assertions="1" classname="scriptnum_tests" name="operators" time="8.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""operators" fixture ctor"
- file: scriptnum_tests.cpp
- line: 178
]]></error><system-err><![CDATA[Failures detected in:
- test case: scriptnum_tests/operators
- file: scriptnum_tests.cpp
- line: 178
]]></system-err>
</testcase>
<testcase assertions="1" classname="serialize_tests" name="sizes" time="8.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""sizes" fixture ctor"
- file: serialize_tests.cpp
- line: 60
]]></error><system-err><![CDATA[Failures detected in:
- test case: serialize_tests/sizes
- file: serialize_tests.cpp
- line: 60
]]></system-err>
</testcase>
<testcase assertions="1" classname="serialize_tests" name="floats_conversion" time="8.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""floats_conversion" fixture ctor"
- file: serialize_tests.cpp
- line: 91
]]></error><system-err><![CDATA[Failures detected in:
- test case: serialize_tests/floats_conversion
- file: serialize_tests.cpp
- line: 91
]]></system-err>
</testcase>
<testcase assertions="1" classname="serialize_tests" name="doubles_conversion" time="8.2e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""doubles_conversion" fixture ctor"
- file: serialize_tests.cpp
- line: 110
]]></error><system-err><![CDATA[Failures detected in:
- test case: serialize_tests/doubles_conversion
- file: serialize_tests.cpp
- line: 110
]]></system-err>
</testcase>
<testcase assertions="1" classname="serialize_tests" name="floats" time="8.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""floats" fixture ctor"
- file: serialize_tests.cpp
- line: 139
]]></error><system-err><![CDATA[Failures detected in:
- test case: serialize_tests/floats
- file: serialize_tests.cpp
- line: 139
]]></system-err>
</testcase>
<testcase assertions="1" classname="serialize_tests" name="doubles" time="8.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""doubles" fixture ctor"
- file: serialize_tests.cpp
- line: 156
]]></error><system-err><![CDATA[Failures detected in:
- test case: serialize_tests/doubles
- file: serialize_tests.cpp
- line: 156
]]></system-err>
</testcase>
<testcase assertions="1" classname="serialize_tests" name="varints" time="8.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""varints" fixture ctor"
- file: serialize_tests.cpp
- line: 173
]]></error><system-err><![CDATA[Failures detected in:
- test case: serialize_tests/varints
- file: serialize_tests.cpp
- line: 173
]]></system-err>
</testcase>
<testcase assertions="1" classname="serialize_tests" name="varints_bitpatterns" time="8.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""varints_bitpatterns" fixture ctor"
- file: serialize_tests.cpp
- line: 205
]]></error><system-err><![CDATA[Failures detected in:
- test case: serialize_tests/varints_bitpatterns
- file: serialize_tests.cpp
- line: 205
]]></system-err>
</testcase>
<testcase assertions="1" classname="serialize_tests" name="compactsize" time="8.2e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""compactsize" fixture ctor"
- file: serialize_tests.cpp
- line: 226
]]></error><system-err><![CDATA[Failures detected in:
- test case: serialize_tests/compactsize
- file: serialize_tests.cpp
- line: 226
]]></system-err>
</testcase>
<testcase assertions="1" classname="serialize_tests" name="vector_bool" time="8.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""vector_bool" fixture ctor"
- file: serialize_tests.cpp
- line: 256
]]></error><system-err><![CDATA[Failures detected in:
- test case: serialize_tests/vector_bool
- file: serialize_tests.cpp
- line: 256
]]></system-err>
</testcase>
<testcase assertions="1" classname="serialize_tests" name="noncanonical" time="8.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""noncanonical" fixture ctor"
- file: serialize_tests.cpp
- line: 265
]]></error><system-err><![CDATA[Failures detected in:
- test case: serialize_tests/noncanonical
- file: serialize_tests.cpp
- line: 265
]]></system-err>
</testcase>
<testcase assertions="1" classname="serialize_tests" name="insert_delete" time="8.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""insert_delete" fixture ctor"
- file: serialize_tests.cpp
- line: 302
]]></error><system-err><![CDATA[Failures detected in:
- test case: serialize_tests/insert_delete
- file: serialize_tests.cpp
- line: 302
]]></system-err>
</testcase>
<testcase assertions="1" classname="serialize_tests" name="check_backward_compatibility" time="8.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""check_backward_compatibility" fixture ctor"
- file: serialize_tests.cpp
- line: 385
]]></error><system-err><![CDATA[Failures detected in:
- test case: serialize_tests/check_backward_compatibility
- file: serialize_tests.cpp
- line: 385
]]></system-err>
</testcase>
<testcase assertions="1" classname="serialize_tests" name="class_methods" time="8.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""class_methods" fixture ctor"
- file: serialize_tests.cpp
- line: 402
]]></error><system-err><![CDATA[Failures detected in:
- test case: serialize_tests/class_methods
- file: serialize_tests.cpp
- line: 402
]]></system-err>
</testcase>
<testcase assertions="1" classname="sighash_tests" name="sighash_test" time="8.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""sighash_test" fixture ctor"
- file: sighash_tests.cpp
- line: 120
]]></error><system-err><![CDATA[Failures detected in:
- test case: sighash_tests/sighash_test
- file: sighash_tests.cpp
- line: 120
]]></system-err>
</testcase>
<testcase assertions="1" classname="sighash_tests" name="sighash_from_data" time="8.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""sighash_from_data" fixture ctor"
- file: sighash_tests.cpp
- line: 163
]]></error><system-err><![CDATA[Failures detected in:
- test case: sighash_tests/sighash_from_data
- file: sighash_tests.cpp
- line: 163
]]></system-err>
</testcase>
<testcase assertions="1" classname="sigopcount_tests" name="GetSigOpCount" time="8.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""GetSigOpCount" fixture ctor"
- file: sigopcount_tests.cpp
- line: 27
]]></error><system-err><![CDATA[Failures detected in:
- test case: sigopcount_tests/GetSigOpCount
- file: sigopcount_tests.cpp
- line: 27
]]></system-err>
</testcase>
<testcase assertions="1" classname="skiplist_tests" name="skiplist_test" time="8.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""skiplist_test" fixture ctor"
- file: skiplist_tests.cpp
- line: 16
]]></error><system-err><![CDATA[Failures detected in:
- test case: skiplist_tests/skiplist_test
- file: skiplist_tests.cpp
- line: 16
]]></system-err>
</testcase>
<testcase assertions="1" classname="skiplist_tests" name="getlocator_test" time="8.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""getlocator_test" fixture ctor"
- file: skiplist_tests.cpp
- line: 45
]]></error><system-err><![CDATA[Failures detected in:
- test case: skiplist_tests/getlocator_test
- file: skiplist_tests.cpp
- line: 45
]]></system-err>
</testcase>
<testcase assertions="1" classname="skiplist_tests" name="findearliestatleast_test" time="8.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""findearliestatleast_test" fixture ctor"
- file: skiplist_tests.cpp
- line: 101
]]></error><system-err><![CDATA[Failures detected in:
- test case: skiplist_tests/findearliestatleast_test
- file: skiplist_tests.cpp
- line: 101
]]></system-err>
</testcase>
<testcase assertions="1" classname="skiplist_tests" name="findearliestatleast_edge_test" time="8.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""findearliestatleast_edge_test" fixture ctor"
- file: skiplist_tests.cpp
- line: 145
]]></error><system-err><![CDATA[Failures detected in:
- test case: skiplist_tests/findearliestatleast_edge_test
- file: skiplist_tests.cpp
- line: 145
]]></system-err>
</testcase>
<testcase assertions="1" classname="streams_tests" name="streams_vector_writer" time="8.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""streams_vector_writer" fixture ctor"
- file: streams_tests.cpp
- line: 13
]]></error><system-err><![CDATA[Failures detected in:
- test case: streams_tests/streams_vector_writer
- file: streams_tests.cpp
- line: 13
]]></system-err>
</testcase>
<testcase assertions="1" classname="streams_tests" name="streams_vector_reader" time="8.2e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""streams_vector_reader" fixture ctor"
- file: streams_tests.cpp
- line: 71
]]></error><system-err><![CDATA[Failures detected in:
- test case: streams_tests/streams_vector_reader
- file: streams_tests.cpp
- line: 71
]]></system-err>
</testcase>
<testcase assertions="1" classname="streams_tests" name="bitstream_reader_writer" time="8.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""bitstream_reader_writer" fixture ctor"
- file: streams_tests.cpp
- line: 116
]]></error><system-err><![CDATA[Failures detected in:
- test case: streams_tests/bitstream_reader_writer
- file: streams_tests.cpp
- line: 116
]]></system-err>
</testcase>
<testcase assertions="1" classname="streams_tests" name="streams_serializedata_xor" time="8.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""streams_serializedata_xor" fixture ctor"
- file: streams_tests.cpp
- line: 151
]]></error><system-err><![CDATA[Failures detected in:
- test case: streams_tests/streams_serializedata_xor
- file: streams_tests.cpp
- line: 151
]]></system-err>
</testcase>
<testcase assertions="1" classname="subsidy_tests" name="block_subsidy_test" time="8.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""block_subsidy_test" fixture ctor"
- file: subsidy_tests.cpp
- line: 15
]]></error><system-err><![CDATA[Failures detected in:
- test case: subsidy_tests/block_subsidy_test
- file: subsidy_tests.cpp
- line: 15
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_threadnames_tests" name="util_threadnames_test_rename_threaded" time="8.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_threadnames_test_rename_threaded" fixture ctor"
- file: util_threadnames_tests.cpp
- line: 53
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_threadnames_tests/util_threadnames_test_rename_threaded
- file: util_threadnames_tests.cpp
- line: 53
]]></system-err>
</testcase>
<testcase assertions="1" classname="timedata_tests" name="util_MedianFilter" time="8.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_MedianFilter" fixture ctor"
- file: timedata_tests.cpp
- line: 12
]]></error><system-err><![CDATA[Failures detected in:
- test case: timedata_tests/util_MedianFilter
- file: timedata_tests.cpp
- line: 12
]]></system-err>
</testcase>
<testcase assertions="1" classname="torcontrol_tests" name="util_SplitTorReplyLine" time="8.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_SplitTorReplyLine" fixture ctor"
- file: torcontrol_tests.cpp
- line: 29
]]></error><system-err><![CDATA[Failures detected in:
- test case: torcontrol_tests/util_SplitTorReplyLine
- file: torcontrol_tests.cpp
- line: 29
]]></system-err>
</testcase>
<testcase assertions="1" classname="torcontrol_tests" name="util_ParseTorReplyMapping" time="8.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_ParseTorReplyMapping" fixture ctor"
- file: torcontrol_tests.cpp
- line: 77
]]></error><system-err><![CDATA[Failures detected in:
- test case: torcontrol_tests/util_ParseTorReplyMapping
- file: torcontrol_tests.cpp
- line: 77
]]></system-err>
</testcase>
<testcase assertions="1" classname="transaction_tests" name="tx_valid" time="8.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""tx_valid" fixture ctor"
- file: transaction_tests.cpp
- line: 89
]]></error><system-err><![CDATA[Failures detected in:
- test case: transaction_tests/tx_valid
- file: transaction_tests.cpp
- line: 89
]]></system-err>
</testcase>
<testcase assertions="1" classname="transaction_tests" name="tx_invalid" time="9.1e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""tx_invalid" fixture ctor"
- file: transaction_tests.cpp
- line: 165
]]></error><system-err><![CDATA[Failures detected in:
- test case: transaction_tests/tx_invalid
- file: transaction_tests.cpp
- line: 165
]]></system-err>
</testcase>
<testcase assertions="1" classname="transaction_tests" name="basic_transaction_tests" time="8.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""basic_transaction_tests" fixture ctor"
- file: transaction_tests.cpp
- line: 242
]]></error><system-err><![CDATA[Failures detected in:
- test case: transaction_tests/basic_transaction_tests
- file: transaction_tests.cpp
- line: 242
]]></system-err>
</testcase>
<testcase assertions="1" classname="transaction_tests" name="test_Get" time="8.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_Get" fixture ctor"
- file: transaction_tests.cpp
- line: 296
]]></error><system-err><![CDATA[Failures detected in:
- test case: transaction_tests/test_Get
- file: transaction_tests.cpp
- line: 296
]]></system-err>
</testcase>
<testcase assertions="1" classname="transaction_tests" name="test_IsStandard" time="0.0001">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_IsStandard" fixture ctor"
- file: transaction_tests.cpp
- line: 322
]]></error><system-err><![CDATA[Failures detected in:
- test case: transaction_tests/test_IsStandard
- file: transaction_tests.cpp
- line: 322
]]></system-err>
</testcase>
<testcase assertions="1" classname="txindex_tests" name="txindex_initial_sync" time="0.000287">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""txindex_initial_sync" fixture ctor"
- file: txindex_tests.cpp
- line: 17
]]></error><system-err><![CDATA[Failures detected in:
- test case: txindex_tests/txindex_initial_sync
- file: txindex_tests.cpp
- line: 17
]]></system-err>
</testcase>
<testcase assertions="1" classname="txvalidation_tests" name="tx_mempool_reject_coinbase" time="0.000158">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""tx_mempool_reject_coinbase" fixture ctor"
- file: txvalidation_tests.cpp
- line: 21
]]></error><system-err><![CDATA[Failures detected in:
- test case: txvalidation_tests/tx_mempool_reject_coinbase
- file: txvalidation_tests.cpp
- line: 21
]]></system-err>
</testcase>
<testcase assertions="1" classname="tx_validationcache_tests" name="tx_mempool_block_doublespend" time="0.000173">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""tx_mempool_block_doublespend" fixture ctor"
- file: txvalidationcache_tests.cpp
- line: 27
]]></error><system-err><![CDATA[Failures detected in:
- test case: tx_validationcache_tests/tx_mempool_block_doublespend
- file: txvalidationcache_tests.cpp
- line: 27
]]></system-err>
</testcase>
<testcase assertions="1" classname="tx_validationcache_tests" name="checkinputs_test" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""checkinputs_test" fixture ctor"
- file: txvalidationcache_tests.cpp
- line: 151
]]></error><system-err><![CDATA[Failures detected in:
- test case: tx_validationcache_tests/checkinputs_test
- file: txvalidationcache_tests.cpp
- line: 151
]]></system-err>
</testcase>
<testcase assertions="1" classname="versionbits_tests" name="versionbits_test" time="6.4e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""versionbits_test" fixture ctor"
- file: versionbits_tests.cpp
- line: 146
]]></error><system-err><![CDATA[Failures detected in:
- test case: versionbits_tests/versionbits_test
- file: versionbits_tests.cpp
- line: 146
]]></system-err>
</testcase>
<testcase assertions="1" classname="versionbits_tests" name="versionbits_computeblockversion" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""versionbits_computeblockversion" fixture ctor"
- file: versionbits_tests.cpp
- line: 234
]]></error><system-err><![CDATA[Failures detected in:
- test case: versionbits_tests/versionbits_computeblockversion
- file: versionbits_tests.cpp
- line: 234
]]></system-err>
</testcase>
<testcase assertions="1" classname="uint256_tests" name="basics" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""basics" fixture ctor"
- file: uint256_tests.cpp
- line: 75
]]></error><system-err><![CDATA[Failures detected in:
- test case: uint256_tests/basics
- file: uint256_tests.cpp
- line: 75
]]></system-err>
</testcase>
<testcase assertions="1" classname="uint256_tests" name="comparison" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""comparison" fixture ctor"
- file: uint256_tests.cpp
- line: 127
]]></error><system-err><![CDATA[Failures detected in:
- test case: uint256_tests/comparison
- file: uint256_tests.cpp
- line: 127
]]></system-err>
</testcase>
<testcase assertions="1" classname="uint256_tests" name="methods" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""methods" fixture ctor"
- file: uint256_tests.cpp
- line: 159
]]></error><system-err><![CDATA[Failures detected in:
- test case: uint256_tests/methods
- file: uint256_tests.cpp
- line: 159
]]></system-err>
</testcase>
<testcase assertions="1" classname="uint256_tests" name="conversion" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""conversion" fixture ctor"
- file: uint256_tests.cpp
- line: 253
]]></error><system-err><![CDATA[Failures detected in:
- test case: uint256_tests/conversion
- file: uint256_tests.cpp
- line: 253
]]></system-err>
</testcase>
<testcase assertions="1" classname="uint256_tests" name="operator_with_self" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""operator_with_self" fixture ctor"
- file: uint256_tests.cpp
- line: 269
]]></error><system-err><![CDATA[Failures detected in:
- test case: uint256_tests/operator_with_self
- file: uint256_tests.cpp
- line: 269
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="util_criticalsection" time="0.000511">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_criticalsection" fixture ctor"
- file: util_tests.cpp
- line: 29
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/util_criticalsection
- file: util_tests.cpp
- line: 29
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="util_ParseHex" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_ParseHex" fixture ctor"
- file: util_tests.cpp
- line: 56
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/util_ParseHex
- file: util_tests.cpp
- line: 56
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="util_HexStr" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_HexStr" fixture ctor"
- file: util_tests.cpp
- line: 77
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/util_HexStr
- file: util_tests.cpp
- line: 77
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="util_FormatParseISO8601DateTime" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_FormatParseISO8601DateTime" fixture ctor"
- file: util_tests.cpp
- line: 101
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/util_FormatParseISO8601DateTime
- file: util_tests.cpp
- line: 101
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="util_FormatISO8601Date" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_FormatISO8601Date" fixture ctor"
- file: util_tests.cpp
- line: 114
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/util_FormatISO8601Date
- file: util_tests.cpp
- line: 114
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="util_FormatISO8601Time" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_FormatISO8601Time" fixture ctor"
- file: util_tests.cpp
- line: 119
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/util_FormatISO8601Time
- file: util_tests.cpp
- line: 119
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="util_ParseParameters" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_ParseParameters" fixture ctor"
- file: util_tests.cpp
- line: 153
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/util_ParseParameters
- file: util_tests.cpp
- line: 153
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="util_GetBoolArg" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_GetBoolArg" fixture ctor"
- file: util_tests.cpp
- line: 189
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/util_GetBoolArg
- file: util_tests.cpp
- line: 189
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="util_GetBoolArgEdgeCases" time="8.2e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_GetBoolArgEdgeCases" fixture ctor"
- file: util_tests.cpp
- line: 228
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/util_GetBoolArgEdgeCases
- file: util_tests.cpp
- line: 228
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="util_ReadConfigStream" time="0.000383">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_ReadConfigStream" fixture ctor"
- file: util_tests.cpp
- line: 281
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/util_ReadConfigStream
- file: util_tests.cpp
- line: 281
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="util_GetArg" time="6.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_GetArg" fixture ctor"
- file: util_tests.cpp
- line: 473
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/util_GetArg
- file: util_tests.cpp
- line: 473
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="util_GetChainName" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_GetChainName" fixture ctor"
- file: util_tests.cpp
- line: 511
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/util_GetChainName
- file: util_tests.cpp
- line: 511
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="util_FormatMoney" time="5.9e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_FormatMoney" fixture ctor"
- file: util_tests.cpp
- line: 588
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/util_FormatMoney
- file: util_tests.cpp
- line: 588
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="util_ParseMoney" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_ParseMoney" fixture ctor"
- file: util_tests.cpp
- line: 613
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/util_ParseMoney
- file: util_tests.cpp
- line: 613
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="util_IsHex" time="0.000462">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_IsHex" fixture ctor"
- file: util_tests.cpp
- line: 666
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/util_IsHex
- file: util_tests.cpp
- line: 666
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="util_IsHexNumber" time="5.9e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_IsHexNumber" fixture ctor"
- file: util_tests.cpp
- line: 681
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/util_IsHexNumber
- file: util_tests.cpp
- line: 681
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="util_seed_insecure_rand" time="6.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_seed_insecure_rand" fixture ctor"
- file: util_tests.cpp
- line: 706
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/util_seed_insecure_rand
- file: util_tests.cpp
- line: 706
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="util_TimingResistantEqual" time="8.1e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_TimingResistantEqual" fixture ctor"
- file: util_tests.cpp
- line: 731
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/util_TimingResistantEqual
- file: util_tests.cpp
- line: 731
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="strprintf_numbers" time="5.9e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""strprintf_numbers" fixture ctor"
- file: util_tests.cpp
- line: 746
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/strprintf_numbers
- file: util_tests.cpp
- line: 746
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="gettime" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""gettime" fixture ctor"
- file: util_tests.cpp
- line: 772
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/gettime
- file: util_tests.cpp
- line: 772
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="util_time_GetTime" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""util_time_GetTime" fixture ctor"
- file: util_tests.cpp
- line: 777
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/util_time_GetTime
- file: util_tests.cpp
- line: 777
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="test_IsDigit" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_IsDigit" fixture ctor"
- file: util_tests.cpp
- line: 798
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/test_IsDigit
- file: util_tests.cpp
- line: 798
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="test_ParseInt32" time="6.1e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_ParseInt32" fixture ctor"
- file: util_tests.cpp
- line: 813
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/test_ParseInt32
- file: util_tests.cpp
- line: 813
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="test_ParseInt64" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_ParseInt64" fixture ctor"
- file: util_tests.cpp
- line: 842
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/test_ParseInt64
- file: util_tests.cpp
- line: 842
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="test_ParseUInt32" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_ParseUInt32" fixture ctor"
- file: util_tests.cpp
- line: 872
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/test_ParseUInt32
- file: util_tests.cpp
- line: 872
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="test_ParseUInt64" time="6.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_ParseUInt64" fixture ctor"
- file: util_tests.cpp
- line: 903
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/test_ParseUInt64
- file: util_tests.cpp
- line: 903
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="test_ParseDouble" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_ParseDouble" fixture ctor"
- file: util_tests.cpp
- line: 935
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/test_ParseDouble
- file: util_tests.cpp
- line: 935
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="test_FormatParagraph" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_FormatParagraph" fixture ctor"
- file: util_tests.cpp
- line: 963
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/test_FormatParagraph
- file: util_tests.cpp
- line: 963
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="test_FormatSubVersion" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_FormatSubVersion" fixture ctor"
- file: util_tests.cpp
- line: 990
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/test_FormatSubVersion
- file: util_tests.cpp
- line: 990
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="test_ParseFixedPoint" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_ParseFixedPoint" fixture ctor"
- file: util_tests.cpp
- line: 1002
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/test_ParseFixedPoint
- file: util_tests.cpp
- line: 1002
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="test_LockDirectory" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_LockDirectory" fixture ctor"
- file: util_tests.cpp
- line: 1105
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/test_LockDirectory
- file: util_tests.cpp
- line: 1105
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="test_DirIsWritable" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_DirIsWritable" fixture ctor"
- file: util_tests.cpp
- line: 1193
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/test_DirIsWritable
- file: util_tests.cpp
- line: 1193
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="test_tracked_vector" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_tracked_vector" fixture ctor"
- file: util_tests.cpp
- line: 1237
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/test_tracked_vector
- file: util_tests.cpp
- line: 1237
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="test_ToLower" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_ToLower" fixture ctor"
- file: util_tests.cpp
- line: 1314
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/test_ToLower
- file: util_tests.cpp
- line: 1314
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="test_ToUpper" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_ToUpper" fixture ctor"
- file: util_tests.cpp
- line: 1328
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/test_ToUpper
- file: util_tests.cpp
- line: 1328
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="test_Capitalize" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_Capitalize" fixture ctor"
- file: util_tests.cpp
- line: 1342
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/test_Capitalize
- file: util_tests.cpp
- line: 1342
]]></system-err>
</testcase>
<testcase assertions="1" classname="util_tests" name="test_spanparsing" time="5.9e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""test_spanparsing" fixture ctor"
- file: util_tests.cpp
- line: 1354
]]></error><system-err><![CDATA[Failures detected in:
- test case: util_tests/test_spanparsing
- file: util_tests.cpp
- line: 1354
]]></system-err>
</testcase>
<testcase assertions="1" classname="coinjoin_tests" name="coinjoin_collateral_tests" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""coinjoin_collateral_tests" fixture ctor"
- file: coinjoin_tests.cpp
- line: 18
]]></error><system-err><![CDATA[Failures detected in:
- test case: coinjoin_tests/coinjoin_collateral_tests
- file: coinjoin_tests.cpp
- line: 18
]]></system-err>
</testcase>
<testcase assertions="1" classname="coinjoin_tests" name="CTransactionBuilderTest" time="6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""CTransactionBuilderTest" fixture ctor"
- file: coinjoin_tests.cpp
- line: 116
]]></error><system-err><![CDATA[Failures detected in:
- test case: coinjoin_tests/CTransactionBuilderTest
- file: coinjoin_tests.cpp
- line: 116
]]></system-err>
</testcase>
<testcase assertions="1" classname="db_tests" name="getwalletenv_file" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""getwalletenv_file" fixture ctor"
- file: db_tests.cpp
- line: 16
]]></error><system-err><![CDATA[Failures detected in:
- test case: db_tests/getwalletenv_file
- file: db_tests.cpp
- line: 16
]]></system-err>
</testcase>
<testcase assertions="1" classname="db_tests" name="getwalletenv_directory" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""getwalletenv_directory" fixture ctor"
- file: db_tests.cpp
- line: 30
]]></error><system-err><![CDATA[Failures detected in:
- test case: db_tests/getwalletenv_directory
- file: db_tests.cpp
- line: 30
]]></system-err>
</testcase>
<testcase assertions="1" classname="db_tests" name="getwalletenv_g_dbenvs_multiple" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""getwalletenv_g_dbenvs_multiple" fixture ctor"
- file: db_tests.cpp
- line: 41
]]></error><system-err><![CDATA[Failures detected in:
- test case: db_tests/getwalletenv_g_dbenvs_multiple
- file: db_tests.cpp
- line: 41
]]></system-err>
</testcase>
<testcase assertions="1" classname="db_tests" name="getwalletenv_g_dbenvs_free_instance" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""getwalletenv_g_dbenvs_free_instance" fixture ctor"
- file: db_tests.cpp
- line: 55
]]></error><system-err><![CDATA[Failures detected in:
- test case: db_tests/getwalletenv_g_dbenvs_free_instance
- file: db_tests.cpp
- line: 55
]]></system-err>
</testcase>
<testcase assertions="1" classname="wallet_tests" name="rescan" time="0.000383">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""rescan" fixture ctor"
- file: wallet_tests.cpp
- line: 41
]]></error><system-err><![CDATA[Failures detected in:
- test case: wallet_tests/rescan
- file: wallet_tests.cpp
- line: 41
]]></system-err>
</testcase>
<testcase assertions="1" classname="wallet_tests" name="importwallet_rescan" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""importwallet_rescan" fixture ctor"
- file: wallet_tests.cpp
- line: 185
]]></error><system-err><![CDATA[Failures detected in:
- test case: wallet_tests/importwallet_rescan
- file: wallet_tests.cpp
- line: 185
]]></system-err>
</testcase>
<testcase assertions="1" classname="wallet_tests" name="coin_mark_dirty_immature_credit" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""coin_mark_dirty_immature_credit" fixture ctor"
- file: wallet_tests.cpp
- line: 253
]]></error><system-err><![CDATA[Failures detected in:
- test case: wallet_tests/coin_mark_dirty_immature_credit
- file: wallet_tests.cpp
- line: 253
]]></system-err>
</testcase>
<testcase assertions="1" classname="wallet_tests" name="ComputeTimeSmart" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""ComputeTimeSmart" fixture ctor"
- file: wallet_tests.cpp
- line: 312
]]></error><system-err><![CDATA[Failures detected in:
- test case: wallet_tests/ComputeTimeSmart
- file: wallet_tests.cpp
- line: 312
]]></system-err>
</testcase>
<testcase assertions="1" classname="wallet_tests" name="LoadReceiveRequests" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""LoadReceiveRequests" fixture ctor"
- file: wallet_tests.cpp
- line: 338
]]></error><system-err><![CDATA[Failures detected in:
- test case: wallet_tests/LoadReceiveRequests
- file: wallet_tests.cpp
- line: 338
]]></system-err>
</testcase>
<testcase assertions="1" classname="wallet_tests" name="ListCoins" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""ListCoins" fixture ctor"
- file: wallet_tests.cpp
- line: 412
]]></error><system-err><![CDATA[Failures detected in:
- test case: wallet_tests/ListCoins
- file: wallet_tests.cpp
- line: 412
]]></system-err>
</testcase>
<testcase assertions="1" classname="wallet_tests" name="CreateTransactionTest" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""CreateTransactionTest" fixture ctor"
- file: wallet_tests.cpp
- line: 632
]]></error><system-err><![CDATA[Failures detected in:
- test case: wallet_tests/CreateTransactionTest
- file: wallet_tests.cpp
- line: 632
]]></system-err>
</testcase>
<testcase assertions="1" classname="wallet_tests" name="select_coins_grouped_by_addresses" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""select_coins_grouped_by_addresses" fixture ctor"
- file: wallet_tests.cpp
- line: 920
]]></error><system-err><![CDATA[Failures detected in:
- test case: wallet_tests/select_coins_grouped_by_addresses
- file: wallet_tests.cpp
- line: 920
]]></system-err>
</testcase>
<testcase assertions="1" classname="wallet_tests" name="wallet_disableprivkeys" time="5.7e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""wallet_disableprivkeys" fixture ctor"
- file: wallet_tests.cpp
- line: 983
]]></error><system-err><![CDATA[Failures detected in:
- test case: wallet_tests/wallet_disableprivkeys
- file: wallet_tests.cpp
- line: 983
]]></system-err>
</testcase>
<testcase assertions="1" classname="wallet_crypto_tests" name="passphrase" time="0.000222">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""passphrase" fixture ctor"
- file: wallet_crypto_tests.cpp
- line: 87
]]></error><system-err><![CDATA[Failures detected in:
- test case: wallet_crypto_tests/passphrase
- file: wallet_crypto_tests.cpp
- line: 87
]]></system-err>
</testcase>
<testcase assertions="1" classname="wallet_crypto_tests" name="encrypt" time="5.9e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""encrypt" fixture ctor"
- file: wallet_crypto_tests.cpp
- line: 103
]]></error><system-err><![CDATA[Failures detected in:
- test case: wallet_crypto_tests/encrypt
- file: wallet_crypto_tests.cpp
- line: 103
]]></system-err>
</testcase>
<testcase assertions="1" classname="wallet_crypto_tests" name="decrypt" time="5.8e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""decrypt" fixture ctor"
- file: wallet_crypto_tests.cpp
- line: 118
]]></error><system-err><![CDATA[Failures detected in:
- test case: wallet_crypto_tests/decrypt
- file: wallet_crypto_tests.cpp
- line: 118
]]></system-err>
</testcase>
<testcase assertions="1" classname="wallet_crypto_tests" name="aes_256_cbc_testvectors" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""aes_256_cbc_testvectors" fixture ctor"
- file: wallet_crypto_tests.cpp
- line: 139
]]></error><system-err><![CDATA[Failures detected in:
- test case: wallet_crypto_tests/aes_256_cbc_testvectors
- file: wallet_crypto_tests.cpp
- line: 139
]]></system-err>
</testcase>
<testcase assertions="1" classname="coinselector_tests" name="bnb_search_test" time="6.3e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""bnb_search_test" fixture ctor"
- file: coinselector_tests.cpp
- line: 123
]]></error><system-err><![CDATA[Failures detected in:
- test case: coinselector_tests/bnb_search_test
- file: coinselector_tests.cpp
- line: 123
]]></system-err>
</testcase>
<testcase assertions="1" classname="coinselector_tests" name="knapsack_solver_test" time="6.1e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""knapsack_solver_test" fixture ctor"
- file: coinselector_tests.cpp
- line: 246
]]></error><system-err><![CDATA[Failures detected in:
- test case: coinselector_tests/knapsack_solver_test
- file: coinselector_tests.cpp
- line: 246
]]></system-err>
</testcase>
<testcase assertions="1" classname="coinselector_tests" name="ApproximateBestSubset" time="5.6e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""ApproximateBestSubset" fixture ctor"
- file: coinselector_tests.cpp
- line: 514
]]></error><system-err><![CDATA[Failures detected in:
- test case: coinselector_tests/ApproximateBestSubset
- file: coinselector_tests.cpp
- line: 514
]]></system-err>
</testcase>
<testcase assertions="1" classname="coinselector_tests" name="SelectCoins_test" time="5.5e-05">
<error message="unexpected exception" type="system error"><![CDATA[
UNCAUGHT EXCEPTION:
- file: unknown location
- line: 0


EXCEPTION STACK TRACE: --------------
signal: SIGABRT (application abort requested)
-------------------------------------

Last checkpoint:
- message: ""SelectCoins_test" fixture ctor"
- file: coinselector_tests.cpp
- line: 537
]]></error><system-err><![CDATA[Failures detected in:
- test case: coinselector_tests/SelectCoins_test
- file: coinselector_tests.cpp
- line: 537
]]></system-err>
</testcase>
</testsuite>